### ISSUE TITLE
Add example to Next.js 

### ISSUE THREAD

**Issue by LoriKarikari** [iaincollins/next-auth#130]
I was thinking that it might be nice to add an example app to the [Next.js examples](https://github.com/zeit/next.js/tree/canary/examples) so it's easy to discover and get feedback. This doesn't have to be now but it can be something when we feel ready for it.

**Comment by ericvrp** [comment]
Yes please that would help me a lot!

**Comment by iaincollins** [comment]
This is a great idea!

I think should leave it till we release version 2.0 publicly, but should submit it for sure!

**Comment by ndom91** [comment]
Example added in this PR: https://github.com/vercel/next.js/pull/14180

Let me know if I should adjust anything. I basically just trimmed down your `next-auth-example` repo page and elaborated a bit in the README, etc.

**Comment by LoriKarikari** [comment]
Maybe you can also add it to [this file](https://github.com/vercel/next.js/tree/canary/examples/with-cookie-auth). I don't know if the Vercel staff updates it or you can add it yourself.

**Comment by ndom91** [comment]
Yeah good call @LoriKarikari, I hadn't even seen that.

I've added us to that README file now in my PR.

**Comment by LoriKarikari** [comment]
@ndom91 I only know about the existence of that file because I've been looking up the auth examples way too many times 😂

**Comment by iaincollins** [comment]
@ndom91 [Hey I see this got merged in!](https://github.com/vercel/next.js/tree/canary/examples/with-next-auth) Congrats and thank you! D 👯
