### ISSUE TITLE
[v2] Mysql database table not generating 

### ISSUE THREAD

**Issue by im-sunil** [iaincollins/next-auth#147]
export const database = {
  name: "default",
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "root",
  password: "",
  database: "test",
  synchronise: true
};

![image](https://user-images.githubusercontent.com/6269292/82673746-e7065700-9c5f-11ea-96cf-07f2a52c9cc2.png)

**Comment by iaincollins** [comment]
Thanks for trying it out and letting us know how you got on! The initial database setup handling - including having to specify `synchronise: true` on first run - definitely needs work
