### ISSUE TITLE
Integrate with JWT API

### ISSUE THREAD

**Issue by wiput1999** [iaincollins/next-auth#153]
Hi,
   I've API that also has auth by JWT can I plug this next-auth to my API?

Thank you

**Comment by LoriKarikari** [comment]
I don't know what your API looks like but you can try creating a custom provider and configure it with your own API. You can find more about this in the provider docs.

**Comment by wiput1999** [comment]
I mean like I've API write with Nest.js that serving JWT Authentication. So can I use it with next-auth?

**Comment by iaincollins** [comment]
So JWT support is definitely something I want to add, and MIGHT make it in for 2.0 (undecided).

However, it's a big tricker to accommodate folks with an existing API, but is very useful to think about as it might shape how the implementation works and what callbacks are exposed.

Could you give a dummy example of what one of your JWT tokens looks like unencrypted?

A screenshot of what cookie it is stored in looks like in a browser inspector (e.g. name, path, prefix, expiry, etc) would also helpful.

**Comment by wiput1999** [comment]
![image](https://user-images.githubusercontent.com/8299278/82813226-d69fe780-9ebe-11ea-8fba-927fe0259dd3.png)
For my API I use Set-Cookie header with httpOnly and secure (on production)

**Comment by iaincollins** [comment]
@wiput1999 Thanks! I'll get back to this ticket in a bit!

**Comment by iaincollins** [comment]
I'm going to track this in  #167 if that's alright.

I have linked back to this issue for reference, but am setting out thoughts there; feel free to chime in if you have any specific requirements or see needs that are not addressed by proposal!
