### ISSUE TITLE
default export vs named exports

### ISSUE THREAD

**Issue by TimNZ** [iaincollins/next-auth#157]
Very trivial general implementation query.

client/index.js exports functions as a default object
```
export default {
  session,
  useSession,
  baseUrl: _baseUrl,
  Provider
}
```

I think you should add named exports as expected/conventional:

```
export {session,useSession,baseUrl,Provider}
```

I was using 'import {useSession} from 'next-auth/client' and trying to figure out why I was erroring.

Same applies to adapters/index.js

```
export default {
  Default: TypeORM.Adapter,
  TypeORM
}

export {Default: TypeORM.Adapter, TypeORM }
```

**Comment by iaincollins** [comment]
Good catch!  The default export behaviour from the modules is as designed, but the CommonJS entry points are wrong. Submitting a fix now to change them.

e.g.
`module.exports = require('./dist/client')`
should be:
`module.exports = require('./dist/client').default`
