### ISSUE TITLE
RFC: Custom page rendering experimenting

### ISSUE THREAD

**Issue by TimNZ** [iaincollins/next-auth#158]
Before I create tests, pull request etc,
please have a look at my draft enhancements to support custom page rendering.

https://github.com/iaincollins/next-auth/compare/master...TimNZ:custom-pages-render

Added support for following options:

* renderPage - a custom pages.render type function handling all aspects of the response
* renderPageContent - custom function to return HTML string content

If a function returns false/null, pages.render will be used for default processing fallback.

The objective was ultimate flexibility and re-use of existing rendering pipeline as fallback.

```
const options = {
  adapter: Adapters.Default(database),
  // renderPage,  // custom renderer function handling all aspects of response
  // renderPageContent // called by pages.render to render string content 
}

function renderPage(req, res, page, props, done) {
  if (page == 'signin')
  {
    res.setHeader('Content-Type', 'text/html')
    res.send(`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><div class="page">SIGN IN</div></body></html>`)
    done()
    return true
  }

}
function renderPageContent ({page}) {
    switch(page)
    {
        case 'signin':
            return `<div>${page}</div>`
    }
}
```

**Comment by iaincollins** [comment]
Thanks for the time!

So, how this one is going to work is that it's going to just be a list of pages, each pointing to a URL.

e.g. 

```javascript
pages: {
  signin: 'http://example.com/signin',
  error:  'http://example.com/error',
  /* etc */
}
```

As sticking to URLs keeps things really simple and works for everyone, regardless of framework (e.g. Vue / Nuxt.js) and reduces the amount of complexity in the API route.
