### ISSUE TITLE
[v2] MySql accessToken Error (Data too long for column)  / sessionExpires (Incorrect date value)

### ISSUE THREAD

**Issue by geraldnolan** [iaincollins/next-auth#160]
Created a new ticket from #156 to track mysql changes.

`  message: "ER_DATA_TOO_LONG: Data too long for column 'accessToken' at row 1",
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'accessToken' at row 1",
  sqlState: '22001',
  index: 0,
  sql: "INSERT INTO `account`(`id`, `providerCompoundId`, `userId`, `providerId`, `providerType`, `providerAccountId`, `refreshToken`, `accessToken`, `accessTokenExpires`) VALUES (DEFAULT, 'c5a81b709cd99e9304181bd96d316bfd8559173e99d6062ac09b52daa3d8669e', 1, 'identityServer', 'oauth', 'b0462468-2ce1-42c1-95d2-4b301637da0d', '01966900197b7b3ee276b221371bec3afd3535c4e7d52b48cd32b3f618c28905', 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkIyRDdFQTM1RjdFRkQwQUFGOTFFRUQ5NTQ1RDYzRkY3ODZBMkIxMEIiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJzdGZxTmZmdjBLcjVIdTJWUmRZXzk0YWlzUXMifQ.eyJuYmYiOjE1OTA0MTY0MzYsImV4cCI6MTU5MDQyMDAzNiwiaXNzIjoiaHR0cHM6Ly9zc28uY2FyZXZhbHVlLmNvbSIsImF1ZCI6ImhmV2YWx1ZS5jb20vcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiY2FyZXZhbHVlLWMyYyIsInN1YiI6ImIwNDYyNDY4LTJjZTEtNDJjMS05NWQyLTRiMzAxNjM3ZGEwZCIsImF1dGhfdGltZSI6MTU5MDIyNzk1OCwiaWRwIjoibG9jYWwiLCJuYW1lIjoiRWxpemFiZXRoIEZpY2Fycm8iLCJnaXZlbl9uYW1lIjoiRWxpemFiZXRoIiwiZmFtaWx5X25hbWUiOiJGaWNhcnJvIiwiZW1haWwiOiJiZXRoLmZpY2Fycm9AZ21haWwuY29tIiwibnBuIjoiMTY4Nzk2MjYiLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicHdkIl19.HVZ7RbOcLYs9IOueFkzbKM5w10zXSqHGsaEiYXfoWjjYqHgVm_hL2P6zK_sH7N3oSf8NZ0ehm-o6htjAcC7-Pf2_ElakXjY3jVr6p1EP4egAbWnhfRpgs6gAnfpo7aXuKstbruI2tRNTzroInbTHR35RiI5Mqqq0lGs3R3YG77xXU9aK0DBte9PW8njyS6K45BmpeR4bpYrGJmCABb6nj0VVlSkYMoZq4jQkuWOoYIvqoXAeUX3CJI2Kr-EYBiH9riu0xYHF6Sbi9D9l1tAoIawin3R3TrwR1JdqHR5vWe-ch6qHAEFc646y9KEiR7A8ys_ojg3CckTUbayOcSyj8Q', NULL)",`

This is why I changed it from:

```
 accessToken: {
      type: 'varchar'
    },
```

to

```
 accessToken: {
      type: 'text'
    },
```

 ```
message: "ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '2020-06-24T14:30:30.181Z' for column 'sessionExpires' at row 1",
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlMessage: "Incorrect date value: '2020-06-24T14:30:30.181Z' for column 'sessionExpires' at row 1",
  sqlState: '22007',
  index: 0,
  sql: "INSERT INTO `session`(`id`, `userId`, `sessionToken`, `sessionExpires`, `accessToken`) VALUES (DEFAULT, 2, '4e724a65e8113d06fcee9a6affdabb83323c7a78fd8e54d7dabc3ef3efdeec34', '2020-06-24T14:30:30.181Z', 'b5d18a738277a6558e9c74a35c9b67c017244e01d73edde5d43046879a1c92c1')",
  name: 'QueryFailedError',
  query: 'INSERT INTO `session`(`id`, `userId`, `sessionToken`, `sessionExpires`, `accessToken`) VALUES (DEFAULT, ?, ?, ?, ?)',
  parameters: [
    2,
    '4e724a65e8113d06fcee9a6affdabb83323c7a78fd8e54d7dabc3ef3efdeec34',
    '2020-06-24T14:30:30.181Z',
    'b5d18a738277a6558e9c74a35c9b67c017244e01d73edde5d43046879a1c92c1'
  ]
}
```

From my knowledge using Date the value would be '2020-06-24'
Where as if you want both date and time you need DateTime.

```
  sessionExpires: {
      type: 'date'
    },

```
```
  sessionExpires: {
      type: 'datetime'
    },

```

I haven't tested if this messes up other adapters.  I was looking at issue #115.  I would love some info on that because it would be nice to be able to change these schema plus group these tables together with a prefix name.

**Comment by iaincollins** [comment]
Thanks! This is being tracked in #147 This should be resolved later today to use `timestamp` (an ANSI compatible specification so works nicely for MySQL, MariaDB, Postgres and others).

**Comment by iaincollins** [comment]
Update: Actually I was just referring to the date time issue above (which was a known issue).

Good catch on the long `accessToken`, thanks!
