### ISSUE TITLE
Added Sign in with apple

### ISSUE THREAD

**Issue by geraldnolan** [iaincollins/next-auth#169]
![image](https://user-images.githubusercontent.com/17180783/82893143-dc460d80-9f50-11ea-89c6-a1be75803afb.png)

I've added **sign in with apple**. Before I create a pull request, would you like this for v2?  
*_The oauth flow is a little bit different, and I wanted to run the changes by you._

A new type was created "**oauth-apple**"  

```
export default (options) => {
    return {
      id: 'apple',
      name: 'Apple',
      type: 'oauth-apple',
      version: '2.0',
      scope: 'name email',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://appleid.apple.com/auth/token',
      authorizationUrl: 'https://appleid.apple.com/auth/authorize?response_type=code&id_token&response_mode=form_post',
      profileUrl: null,
      profile: (profile) => {
        return {
          id: profile.sub,
          name: profile.sub,
          email: profile.email
        }
      },
      ...options
    }
  }
```

To get the user profile, you ask the server for a token, and it providers a jwt id_token to decode.  I had to add jwt-decode as a dependency. 

Also, you need to add response_mode=form_post if you pass in scope parameters according to apple documentation. The callback has to be a POST and not a GET

```
case 'callback':
            if (provider && options.providers[provider]) {
              callback(req, res, options, done)
            } else {
              res.status(400).end(`Error: HTTP POST is not supported for ${url}`)
              return done()
            }
            break
```

The secret has to be encoded as a jwt using your AuthKey_Q6YSW63G.k8 file downloaded from apple developer portal. 

**AppleClientSecret.js** would have to be added to the Developer project to create the jwt secret at runtime. Allowing the dev to have more control on the expiration/settings of the jwt.

The **profileUrl** is set to null.  They do not have an endpoint to get the profile.

Additional documentation would need to be made..

**Comment by iaincollins** [comment]
Oh, outstanding! Yes please, I would love a PR for that!

I appreciate the oAuth code is messy right now. I had to patch in a hacky work around some issues in the `node-oauth` when a change to the Twitch API broke Twitch provider (about a week after we created it! 🤦‍♂️), and I haven't got round to refactoring it to clean it up since.
