### ISSUE TITLE
About access token and scopes

### ISSUE THREAD

**Issue by lluia** [iaincollins/next-auth#180]
First of all, congrats 💯 🎊 💚 , this is a very cool project!

I've been trying to set-up a [Next app that talks to the Github API](https://github.com/lluia/hip-hub) and I found the **beta** of this library by far the nicest and simpler to configure ✨

I did give a try to [Next Auth0](https://github.com/auth0/nextjs-auth0), but it seems by far too complicated for my use-case ( and got lost trying to configure stuff in the **Auth0** dashboard 😂 )

## The issue

I managed to get an app working that connects to Github:
https://github.com/lluia/hip-hub

Taking [`next-auth-example`](https://github.com/iaincollins/next-auth-example) as a base but modifying it to use **Typescript**:

<img src="https://user-images.githubusercontent.com/5938217/83260091-75775d00-a1b9-11ea-8df8-30793cb35d5f.gif" width="500" />

I also [requested more scopes](https://github.com/lluia/hip-hub/blob/master/pages/api/auth/%5B...slug%5D.ts#L11-L12) to be able to query the Github API, which is my next step.

Assuming the **access token** stored in the session is what [Github give us back](8998723e456eb24b06cfe871c3eaa242a1fe53408dfd7e5fa6309126f37eac3e), I'm trying to [CURL the API with it](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#3-use-the-access-token-to-access-the-api) as per the docs but I get the following error:
```
$ curl -H "Authorization: bearer [token]" -X POST -d " \
 { \
   \"query\": \"query { viewer { login }}\" \
 } \
" https://api.github.com/graphql

{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v4"
}
```
In theory, it should work 😅 🤷🏻‍♂️ , appreciate any help with this 🙏🏻

**Comment by LoriKarikari** [comment]
The tokens are stored in the `Accounts`. This also has been discussed [here](https://github.com/iaincollins/next-auth/issues/128#issuecomment-630064064).

**Comment by LoriKarikari** [comment]
@iaincollins maybe I can add this to the OAuth section of the providers docs?

**Comment by lluia** [comment]
Thanks, this should do for now 💯 

I think having it in the docs woulb be useful 🙏🏻

**Comment by iaincollins** [comment]
Thanks for sharing @lluia ! I'm glad it's working out and appreciate the feedback and the question.

@LoriKarikari I think your right! Sounds like it's worth us documenting some example code for now as it seems like a common question

**Comment by leohxj** [comment]
@lluia lluia/hip-hub is not found now.
Do you run your next strp which is use github access_token ,has any repo?
