### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kelleg1** [iaincollins/next-auth#19]
Is this code licensed the same as the Next.js Starter boilerplate (and how is that licensed—I posted the same question in its GitHub repo)?

**Comment by iaincollins** [comment]
Yes, NextAuth and Next.js Starter are both licensed under ISC (an MIT style licence).

This was specified in the package.json but I have now added an explicit LICENCE.txt file.

**Comment by kelleg1** [comment]
Ah yes, I remember reading this in the package.json. Thank you for clarifying.
