### ISSUE TITLE
Provide a generic interface for non-Next.js projects?

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#2]
While the goal of this project is to be make it easier to add authentication to Next.js projects, it could also be used with other React projects that don't use Next.js - as it doesn't use any Next.js specific hooks under the hood.

Crucially, there would need to be an example of how to consume NextAuth.init() in whatever the equivalent of getInitialProps() is in the Server Side Rendering system being used.

If anyone would like to see this, suggestions and input is welcome.

**Comment by LoriKarikari** [comment]
@iaincollins can this one be closed? It doesn't have a milestone assigned.

**Comment by iaincollins** [comment]
@LoriKarikari I think closing it probably makes sense.

I'd still like to do this, but probably better to revisit with more context and detail.
