### ISSUE TITLE
Pass req object to sendSignInEmail function

### ISSUE THREAD

**Issue by franciclo** [iaincollins/next-auth#20]
The package allows for a custom function for sending the sign in email, but to create the email i also need access to the `req.locale` variable that is being set by a middleware based on the `Accept-Language` headers sent by the browser and the supported locales of the app.
Is there other way to accomplish this?

**Comment by iaincollins** [comment]
Oops! Sorry it's supposed to be passed to it already (in a not very well documented feature) but looks like it's not being by mistake. Will resolve!

**Comment by iaincollins** [comment]
This is now in 1.8.0 which I've just published to NPM.

I've added a new custom signIn() option too, and req is also passed to it for the same reasons.

**Comment by franciclo** [comment]
Great thanks! will be trying it out!
