### ISSUE TITLE
Getting provider id from providers route

### ISSUE THREAD

**Issue by ehrhart** [iaincollins/next-auth#207]
Using the [providers()](https://next-auth.js.org/getting-started/client#providers) method currently returns an object with:

```js
{
  name,
  type,
  signinUrl,
  callbackUrl
}
```

However, the object is missing the `id` property. This property is needed for matching a provider with a user account's `providerId` field.

Would it be possible to add the provider id to the `providers()` method?

**Comment by iaincollins** [comment]
The key for each provider is currently the ID, but if that's not obvious or potentially confusing (which it probably isn't, given you are asking about it!) I don't see why we couldn't add that.

While technically might be redundant, it's not like this route is called unless explicitly invoked, and is potentially more obvious if it's included in the response.

**Comment by ehrhart** [comment]
Oops, I don't know how I missed that 😄 

It might be enough to just provide an example of the object structure in the documentation then.

**Comment by iaincollins** [comment]
I've added the ID to the response so it's clearer for everyone in future!
