### ISSUE TITLE
Mongoose schema

### ISSUE THREAD

**Issue by edward-hong** [iaincollins/next-auth#21]
Hi, instead of the mongodb package, I would like to use mongoose instead. I was wondering what would the mongoose schema be for the user model?

**Comment by edward-hong** [comment]
I just need oAuth authentication from one provider and mongoose taking care of my database. So I stripped away all the unnecessary code. 

In the `.env` file I've got `MONGO_URI`, `FACEBOOK_ID` and `FACEBOOK_SECRET` filled.

The 'Sign in' button on the client points to `/auth/oauth/facebook` and I only have `callback.js` in the auth folder. So I click the button, the app goes to /auth/callback and then back to the index file.

I then tried replacing the Mongodb configuration with Mongoose. Here is my code for `next-auth.functions.js` file:

```
require('dotenv').load()
const mongoose = require('mongoose')

const User = require('./models/User')

module.exports = () => {
	return new Promise((resolve, reject) => {
		mongoose.connect(process.env.MONGO_URI).then(() => {
			return Promise.resolve({
				find: ({ id, email, emailToken, provider } = {}) => {
					let query = {}

					if (id) {
						query = { _id: MongoObjectId(id) }
					} else if (email) {
						query = { email: email }
					} else if (emailToken) {
						query = { emailToken: emailToken }
					} else if (provider) {
						query = { [`${provider.name}.id`]: provider.id }
					}

					return new Promise((resolve, reject) => {
						User.findOne(query)
							.then(user => resolve(user))
							.catch(err => reject(err))
					})
				},

				insert: (user, oAuthProfile) => {
					return new Promise((resolve, reject) => {
						new User(user)
							.save()
							.then(user => resolve(user))
							.catch(err => reject(err))
					})
				},

				update: (user, profile) => {
					return new Promise((resolve, reject) => {
						User.findByIdAndUpdate(user._id, user)
							.then(() => resolve(user))
							.catch(err => reject(err))
					})
				},

				serialize: user => {
					if (user.id) {
						return Promise.resolve(user.id)
					} else if (user._id) {
						return Promise.resolve(user._id)
					} else {
						return Promise.reject(new Error('Unable to serialise user'))
					}
				},

				deserialize: id => {
					return new Promise((resolve, reject) => {
						User.findById(id)
							.then(user => {
								if (!user) return resolve(null)

								return resolve({
									id: user._id,
									name: user.name,
									email: user.email,
									emailVerified: user.emailVerified,
									admin: user.admin || false
								})
							})
							.catch(err => resolve(err))
					})
				}
			})
		})
	})
}
```

Again note that there's no remove function. The reason is prior to implementing mongoose, the example still worked without the remove function and I don't need the option of users cancelling their account. This is my User model set up: 

```
const mongoose = require('mongoose')
const { Schema } = mongoose

const userSchema = new Schema({
	name: String,
	email: String,
	facebook: {
		id: String,
		accessToken: String,
		refreshToken: String
	}
})

const Users = mongoose.model('user', userSchema)

module.exports = Users
```

I derived this schema from looking at the database directly and seeing what information was being inserted.

When I run `npm run dev` it says the code has compiled successfully in the terminal. But when I go to localhost:3000,  I get: 

This site can’t be reached
localhost refused to connect.

So the server won't start.

After console logging in several places to see where the problem is, if I put a console log in the `next-auth.config.js` file:

```
module.exports = () => {
	return nextAuthFunctions().then(functions => {
                console.log(functions)
		return new Promise((resolve, reject) => {
			...
		})
	})
}
```

I don't see functions logged in the terminal when the code runs. So the functions promise isn't being resolved. Can someone please help with this issue? Here's a [link](https://github.com/edward-hong/next-auth-example/tree/master/example) to my code

**Comment by edward-hong** [comment]
Never mind I've solved the issue and it's working correctly. Thank you for the awesome package!

**Comment by serjt12** [comment]
I' facing the same issue, could you share how you solve this, thank you in advanced.

**Comment by edward-hong** [comment]
Hi @serjt12, I don't remember but here's the [repo](https://github.com/edward-hong/night-life-app) where I encountered this problem.

**Comment by serjt12** [comment]
Thanks a lot for your answer, I checked your repo but it was having the same issue, thanks anyway...

**Comment by edward-hong** [comment]
I made the assumption that you wanted a solution that involved this `next-auth` module. I recently updated my app and eventually decided to just stick with `passport.js` without `next-auth`. Here's the [repo](https://github.com/edward-hong/roamm) if you're interested in going that route.

**Comment by serjt12** [comment]
Thank you very much @edward-hong  I really appreciate your answer, I will check it out...
