### ISSUE TITLE
Could not find a declaration file for module 'next-auth/client'

### ISSUE THREAD

**Issue by ricjohn-acosta** [iaincollins/next-auth#210]
I seem to be getting the following error when importing next-auth: 

```
module "c:/Users/-/PersonalProjects/joba2b/node_modules/next-auth/client"
Could not find a declaration file for module 'next-auth/client'. 'c:/Users/-/PersonalProjects/joba2b/node_modules/next-auth/client.js' implicitly has an 'any' type.
  Try `npm install @types/next-auth` if it exists or add a new declaration (.d.ts) file containing `declare module 'next-auth/client';`ts(7016)
```

I'm on version 2.0.0-beta.61 and I used https://github.com/iaincollins/next-auth-example as a reference. I did find a similar issue from 2 years ago https://github.com/iaincollins/next-auth/issues/35 but I'm pretty sure my imports are correct. 

e.g: ` import { Provider } from "next-auth/client" `

Any ideas on how to fix this?

**Comment by LoriKarikari** [comment]
next-auth doesn't provide any typings for Typescript yet that's why you are getting that error. You can add `declare module 'next-auth/client';` to `index.d.ts` and it should work.

**Comment by ricjohn-acosta** [comment]
works now cheers!

**Comment by olserra** [comment]
@LoriKarikari coudn't make this work. I have to declare it like an import, as you wrote? Simple as that?

**Comment by LoriKarikari** [comment]
@olserra you can add `index.d.ts` to the root of your project and add the declaration to it.

**Comment by olserra** [comment]
Thanks @LoriKarikari ! That's what I did right after wrote this comment. As simple as that :)

But, I am facing another issue now. On _app.tsx I have:
```

Module not found: Can't resolve 'next-auth/client'
> 1 | import {Provider} from 'next-auth/client';
```

**Comment by keshprad** [comment]
I have the same issue as @olserra. 
For the time being, I downgraded from next-auth@4.0.6 to next-auth@4.0.0

**Comment by keshprad** [comment]
@olserra 
I had the same issue. 
I think you might be on next-auth v4 while looking at the v3 documentation.

Instead try:
```
import { SessionProvider } from 'next-auth/react';
```

**Comment by a2zarslaan** [comment]
> I had the same issue. I think you might be on next-auth v4 while looking at the v3 documentation.
This had me struggling for a bit, thank you for pointing this out!

**Comment by thalysmcarrara** [comment]
in version 4 the import directory of signIn is >>>> "import { signIn } from "next-auth/react"

**Comment by MSKU786** [comment]
Checkout your version if it's v4 then {signIn, singOut, useSession} form "next-auth/react"  and it will work
