### ISSUE TITLE
Add ability to modify jwt content

### ISSUE THREAD

**Issue by devilcoders** [iaincollins/next-auth#217]
Hey! 👋 

I was wondering if it is considered to add JWT customization functionality. I need this to make it work with [Hasura](https://hasura.io/) and possibly [DGraph](https://dgraph.io/). 

Thanks!

**Comment by iaincollins** [comment]
There is an open issue for this here #215

**Comment by iaincollins** [comment]
(This should be possible, so you can easily inject data into and read from the decrypted / signed token, and also optionally define your own routines for doing that, if you need to.)

**Comment by devilcoders** [comment]
Nice, thanks!
