### ISSUE TITLE
Team to decide what platform to use for internal discussions

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#225]
We (contributors) need a way to talk to each other directly - and as a closed group, to avoid discussions getting too confusing for end users if we want to be able to throw ideas around together safely in a semi-private space; including discussing the roadmap / what we want to work on / what needs addressing / how we collaborate etc.

I personally don't mind if it's public as long as as only contributors can post.

What do existing contributors think?

## Options

* GitHub Discussions - This in beta, I am not sure if it allows for private / moderated channels?
* GitHub Teams - I would be happy to pay for something and/or move to GitHub org if required
* Discord
* ???

**Comment by LoriKarikari** [comment]
For me personally it doesn't matter but I can imagine that some people don't use Discord and it might be a bit of an overhead to using an extra app. So maybe it's best to keep this stuff on Github as we are all using it anyway?

**Comment by ndom91** [comment]
Yeah I think github discussions would be perfect for this. Github activated it for `vercel/next.js` itself already, you can take a look here: https://github.com/vercel/next.js/discussions

I dont think there is any sort of ETA on launch for this, so do you guys think its worth waiting it out or should we look for something else in the mean time? Do you want to definitely have something up once you bring 2.0 out of beta?

We have to consider also the cost of moving if we plan on using something else in the mean time and then moving to Github Discussions down the line.. Or if we just stick to that "something else".

**Comment by ndom91** [comment]
What do you guys think about using [Spectrum](https://spectrum.chat) for now? Theres a chat channel and they have more traditional threaded channel type things. It got bought by Github in 2018 so it'll probably be folded into Github eventually anyway. Next.js themselves have a community channel there as well (https://spectrum.chat/next-js).

I reserved our name there at least and made a "community" - https://spectrum.chat/next-auth

Take a look and let me know what you guys think. If you like it you can join and I can make you admins, etc.

**Comment by ndom91** [comment]
@LoriKarikari I saw you joined the spectrum channel, what do you think?

**Comment by iaincollins** [comment]
@ndom91 Thanks for the poke on this!

Hey, I was thinking of making the repo into a GitHub org. I have some news I think you will like I'd like to share with you.

(I wanted to do this before but couldn't as my access was broken (!) but GitHub say they just fixed it!)

I'm happy with Spectrum (thanks for doing that), but given GitHub has acquired GitHub orgs come with private team boards now, do you think we should move this repo to an org and use team? 

If you are all happy with moving to an org I will do that and add you all! :-)

cc @LoriKarikari @geraldnolan @Fumler @JeffersonBledsoe

**Comment by iaincollins** [comment]
@ndom91 Sorry I didn't look at this sooner! I've been busily kept up with worrying about bugs in 2.0 XD 

(Thankfully, most issue seem relatively small!)

Oh the automated publish-on-release workflow worked great on 2.2 yesterday BTW! Thanks!

**Comment by ndom91** [comment]
Yeah no worries, I realize theres a ton of stuff that came in the past week or two.

Regarding communication - if we can keep it in the repo / org on Github then thats even easier. I'm all for it!

**Comment by iaincollins** [comment]
What if:

* We move to an org and use that for private convos
* Use Spectrum for support / public convos

"Bug reports" from folks new to Next.js (and still grappling with stuff like environment variables, app.js, etc) are quite common and would be good to shift the convo somewhere they can more easily self-serve.

**Comment by ndom91** [comment]
We don't have to use spectrum, it was just a suggestion. I think splitting it over two services / locations may be unnecessarily complex. What if we just have a column on the board for the more basic self-serve type questions / "bug reports" ?

**Comment by iaincollins** [comment]
We have a GitHub Org / Team now!
