### ISSUE TITLE
Improve appearance of built-in pages on mobile

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#231]
They are serviceable - they are responsive and work okay - but the text layout on smaller displays / mobile devices could be better. This is a minor cosmetic change.

I'd like to do a pass on the font sizes, line height and padding using so that pages look a bit better on mobile (e.g. slightly increased line heights and button sizes). There might be some scope for improving the text of the error messages themselves too.

As part of this I would also like to update the custom pages documentation to document all the error message that a custom error page might be passed

**Comment by ndom91** [comment]
I can definitely do this. Let me take a look this evening when I'm home from work :+1:

**Comment by iaincollins** [comment]
Hey I did a quick pass just for fun, but let me know if you have any feedback. :-)

**Comment by ndom91** [comment]
Hey sorry I never got around to this, been super busy this weekend! But it looks good to me, I like the accessibility border on `:focus` !
