### ISSUE TITLE
Bad Authentication data.

### ISSUE THREAD

**Issue by shamoons** [iaincollins/next-auth#232]
I have:
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  site: process.env.SITE || 'http://localhost:3000',

  // configure one or more authentication providers
  providers: [
    Providers.Twitter({
      clientId: process.env.TWITTER_CONSUMER_KEY,
      clientSecret: process.env.TWITTER_CONSUMER_SECRET
    }),
  ],

  // database is optional, but required to persist accounts in a database
  database: process.env.DATABASE_URL,

  // control who can sign in - allows access control even without a database
  allowSignin: async (user, account) => { return true }
}

export default (req, res) => NextAuth(req, res, options)
```

but get the following errors:
```
GET_AUTHORISATION_URL_ERROR {
  statusCode: 400,
  data: '{"errors":[{"code":215,"message":"Bad Authentication data."}]}'
}
OAUTH_SIGNIN_ERROR {
  statusCode: 400,
  data: '{"errors":[{"code":215,"message":"Bad Authentication data."}]}'
}
GET_AUTHORISATION_URL_ERROR {
  statusCode: 400,
  data: '{"errors":[{"code":215,"message":"Bad Authentication data."}]}'
}
OAUTH_SIGNIN_ERROR {
  statusCode: 400,
  data: '{"errors":[{"code":215,"message":"Bad Authentication data."}]}'
}
```

**Comment by iaincollins** [comment]
I think this is probably down to either the client ID / secret being incorrect - or possibly old (for a previous version of Twitter OAuth) or not activated yet somehow.

Apart from checking the ID and Secret, other things to check are if your Twitter account is verified.

Sometimes accounts don't work unless activated (e.g. via email or have mobile details associated with them). I am not sure what the current requirements for Twitter are, but I have seen OAuth details fail to work for making API calls on new accounts that were not fully activated yet somehow, and the error handling from providers is not always very good.

**Comment by shamoons** [comment]
I'm using:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1019677/84056653-7f9d1680-a984-11ea-8443-16c6ae8e8a88.png">

(don't worry - I regenerated). I assume the KEY is the ID?

**Comment by iaincollins** [comment]
Thanks!

Yeah Twitter call it Key for some reason, but everyone else calls it Client ID.

Hmm that looks good. Did you enable getting email address under the Permissions tab?

**Comment by shamoons** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1019677/84059577-d73d8100-a988-11ea-8b68-fa32b2889e93.png">
Yup - got that setup too =(

**Comment by iaincollins** [comment]
That looks good. I'm not sure what is going on here.

If you wanted to set up new credentials and share details with me via email to me@iaincollins.com I'd be happy to look and let you know if they work for me.

**Comment by shamoons** [comment]
Thanks for helping!
