### ISSUE TITLE
Add support to the mongodb+srv

### ISSUE THREAD

**Issue by anzileiro** [iaincollins/next-auth#239]
Add support to connect with mongodb+srv pattern such as clusters.

**Comment by anzileiro** [comment]
mongodb://user:passworda@some-shard-00-00-xxx.mongodb.net:27017,some-shard-00-01-xxx.mongodb.net:27017,some-shard-00-02-xxx.mongodb.net:27017/some?ssl=true&replicaSet=some-shard-0&authSource=admin&retryWrites=true

Or

mongodb+srv://user:password@some-xxx.mongodb.net/some?retryWrites=true&w=majority

**Comment by anzileiro** [comment]
I tried this without connection string but object configuration
` database: {
    type: 'mongodb',
    url: 'mongodb+srv://user:pass@some-xxx.mongodb.net/azdata?retryWrites=true&w=majority',
    ssl: true,
    authSource: 'admin',
    replicaSet: 'some-shard-0'
  },
`

**Comment by iaincollins** [comment]
Thanks for raising this issue, have addressed it in PR #288 so that this workaround should no longer be required (but will still work fine if you are doing it!)
