### ISSUE TITLE
How to get contents of encrypted JWT token?

### ISSUE THREAD

**Issue by lnikell** [iaincollins/next-auth#243]
What could be the best way of getting encrypted JWT token on the server-side and client-side?
There could be a need to pass JWT token further down to another API service.
Currently, I found the way to sign JWT decrypted token again using session config in [...nextauth].js file
```
  session: {
    jwt: true,
    get: async (session, decryptedToken) => {
      session.token = await jwt.encode({
        secret:  "" ,
        token: decryptedToken,
        maxAge: 24 * 60 * 60,
      });
      return session;
    },
  },
```

**Comment by iaincollins** [comment]
The `session.get()` callback allows you to return custom data to the front end, such as from a database or encrypted in a JWT, but you cannot modify the JWT from it.

The callback `jwt.set()` allows you to read and to modify the JWT and is also called when a session is checked. Any changes made to the token there are saved in the encrypted JWT.

The `session.get()` callback does not currently let you modify the JWT or resign it but this might change in future if is merged with behaviour of `jwt.set()`.

Note: Both these callbacks may be renamed in future, but the functionality will remain the same.

You can also read a JWT from an API route, like this:

```js
import jwt from 'next-auth/jwt'

const secret = process.env.JWT_SECRET

export default async (req, res) =>  {
  // Automatically decrypts and verifies JWT
  const token = await jwt.getJwt({ req, secret })
  res.end(JSON.stringify(token, null, 2))
}
```

Note: The secret needs to match the secret set for `jwt.secret`.

**Comment by lnikell** [comment]
@iaincollins I have a question and proposal. 
I guess it's a common practice to send JWT tokens further down to different API services. Currently in the session as far as I understand you store signed JWT then encrypted by AES algorithm using again secret.
I guess you do it for security reasons to don't store token by itself on client side that could be used for access as well. So I think it could be good to add extra options to retrieve original encrypted token from the server-side.  I will send you PR for this.

**Comment by Pixelatex** [comment]
I found this issue while searching for a way to get the original un-decrypted JWT-token.

getJWT is not an actual function and was probably renamed? There is no reference on it anywhere.

I'm posting my solution here for others that arrive to this issue via searching:

```
  const token = await jwt
    .getToken({ req, secret, raw: true })
    .catch((e) => console.error(e))
  res.send(JSON.stringify(token, null, 2))
```
So yes, simply adding the `raw` option does the trick.
p.s. this only works if you define a secret in the nextAuth options for signing the JWT!! spend way too long looking for why it was failing.


p.p.s. @iaincollins could you please document this whole ordeal better?

**Comment by balazsorban44** [comment]
I wonder if Iain just forgot the name. It is called `getToken`

**Comment by jfernandez** [comment]
+1 on documenting how to get the raw JWT. It's very common practice to send that encrypted JWT to API servers

**Comment by asifsaho** [comment]
> 

thanks for sharing the code, can you write a bit where to put this code?

**Comment by asifsaho** [comment]
> I found this issue while searching for a way to get the original un-decrypted JWT-token.
> 
> getJWT is not an actual function and was probably renamed? There is no reference on it anywhere.
> 
> I'm posting my solution here for others that arrive to this issue via searching:
> 
> ```
>   const token = await jwt
>     .getToken({ req, secret, raw: true })
>     .catch((e) => console.error(e))
>   res.send(JSON.stringify(token, null, 2))
> ```
> 
> So yes, simply adding the `raw` option does the trick. p.s. this only works if you define a secret in the nextAuth options for signing the JWT!! spend way too long looking for why it was failing.
> 
> p.p.s. @iaincollins could you please document this whole ordeal better?

thanks for sharing the code, can you write a bit where to add this code? I am a bit confused as it requires the `req` object.

**Comment by pdevito3** [comment]
> @iaincollins I have a question and proposal.
I guess it's a common practice to send JWT tokens further down to different API services. Currently in the session as far as I understand you store signed JWT then encrypted by AES algorithm using again secret.
I guess you do it for security reasons to don't store token by itself on client side that could be used for access as well. So I think it could be good to add extra options to retrieve original encrypted token from the server-side. I will send you PR for this.

Seconding this and others in this post. The current functionality passes the encrypted token to my api, returning a 401 and making this entire setup useless. [Trying to figure out how to make this work](https://github.com/nextauthjs/next-auth/discussions/5214) is incredibly painful.
