### ISSUE TITLE
getJWT throws an error

### ISSUE THREAD

**Issue by lnikell** [iaincollins/next-auth#244]
I'm using the current master version and nextjs 9.4.4. I tried to use getJwt method as described in the documentation and got an error that can't get '__Secure-next-auth.session-token' of undefined. During the investigation I found a bug that in the source code:
```
const getJwt = async ({ req, secret, cookieName }) => {
  if (!req || !secret) throw new Error("Must pass { req, secret } to getJWT()");
  const secureCookieName = "__Secure-next-auth.session-token";
  const insecureCookieName = "next-auth.session-token";
  const cookieValue = cookieName
    ? req.cookies[cookieName]
    : req.cookies[insecureCookieName];

  if (!cookieValue) {
    return null;
  }
```
req.cookies used however cookies stored in req.headers.cookie object

**Comment by iaincollins** [comment]
The function `req.cookies` middleware is [built-in to Next.js](https://nextjs.org/docs/api-routes/api-middlewares) and is also is used internally by NextAuth.js. If the `getJwt()` function isn't working it would be helpful to provide an example of how you are using it.

**Comment by iaincollins** [comment]
I've just [checked the source](https://github.com/iaincollins/next-auth/blob/master/src/lib/jwt.js) and that source code above doesn't match the source of the `getJwt()` method in master, or any version of it from source control so I'm not sure where it comes from.

This is the only version of the `getJwt()` function in the history for the master branch:

```js
const getJwt = async ({ req, secret, cookieName }) => {
  if (!req || !secret) throw new Error('Must pass { req, secret } to getJWT()')

  const secureCookieName = '__Secure-next-auth.session-token'
  const insecureCookieName = 'next-auth.session-token'
  const cookieValue = cookieName ? req.cookies[cookieName] : req.cookies[secureCookieName] || req.cookies[insecureCookieName]

  if (!cookieValue) { return null }

  try {
    return await decode({ secret, token: cookieValue })
  } catch (error) {
    return null
  }
}
```

**Comment by iaincollins** [comment]
The the live demo at [next-auth-example.now.sh](https://next-auth-example.now.sh/) has been updated to use this method as a practical example of how to implement the usage as shown in the documentation.

Once signed in, you can view the decrypted JWT for your session here:
[next-auth-example.now.sh/api/jwt-example](https://next-auth-example.now.sh/api/jwt-example)

You view the source for this route at [next-auth-example/api/jwt-example.js](https://github.com/iaincollins/next-auth-example/blob/master/pages/api/jwt-example.js)

**Comment by lnikell** [comment]
@iaincollins thank you for the answer. My mistake was that I tried to use it within getServerSideProps just to check how does it work and what is the result in return. Now I understand that it works only within API routes where cookies middleware exists.
