### ISSUE TITLE
New Callbacks / Events system

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#247]
**Summary of proposed feature**

We should have more complete and consistent events / callback system.

**Purpose of proposed feature**

It helps addresses issues raised in #100 and other issues people have raised with regard to auditing and customisation of behaviour, by providing a consistent approach for the entire application for all events / callbacks.

**Detail of the proposed**

It is proposed to remove the current methods:

* `allowSignin()`
* `allowCallbackURL()`
* `session.get()`
* `jwt.set()`

And replace them with new methods, as `callbacks` and `events`:

### Callbacks 

Callbacks are asynchronous functions that return a response that can be used to control application. behaviour.

For example, allowing a user to sign in or or not, changing a URL a user is about to redirected to, or altering the contents of  Session object or JSON Web Token before it is returned.
 
```js
callbacks: {
  signin,
  redirect,
  session,
  jwt
}
```

### Events

Events are asynchronous functions that do not return a response.

They are useful for audit logging.

```js
events: {
  signin,
  signout,
  createUser,
  linkAccount,
  session,
  error
}
```

**Potential problems**

This is a breaking change, but the options being removed would have very similar replacements.

**Describe any alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by iaincollins** [comment]
Additional events will be added in future, as features are added to 2.0 (e.g. unlinking accounts, deleting accounts, etc).

**Comment by shamoons** [comment]
Any example of how to actually use these new events?

**Comment by iaincollins** [comment]
They are documented here https://next-auth.js.org/configuration/callbacks

There is an example of using the signin callback in the comments of this issue:
https://github.com/iaincollins/next-auth/issues/266

At some point will get around to creating some examples of how to use them for specific problems that come up a lot (e.g. accessing Refresh or Access Tokens).

**Comment by shamoons** [comment]
What about an example for `events`

**Comment by iaincollins** [comment]
They work the same way, but are much simpler.

This is also covered in the documentation. 

https://next-auth.js.org/configuration/options#events

**Comment by iaincollins** [comment]
I think we will write some tutorial articles / blog posts in a bit, that show how to use the features more clearly in practice, probably after launch, once the API is final :-)
