### ISSUE TITLE
npm run build error: Can't resolve 'mongodb' in node_modules\next-auth\dist\adapters\typeorm

### ISSUE THREAD

**Issue by lazordiak** [iaincollins/next-auth#251]
Hello! I checked out the latest version of the next-auth example and copied the code almost exactly into a project based on the [RealWorld Next app](https://github.com/reck1ess/next-realworld-example-app), but when I tried ```npm run build``` I got the following error: 

```Module not found: Can't resolve 'mongodb' in 'C:\Users\lazor\Desktop\app\node_modules\next-auth\dist\adapters\typeorm'```

I'm confused since MongoDB's not a dependency for our project; I thought maybe the error was due to the way sqlite was used in the example app, but I removed sqlite from the .env file and the database option from ```[...nextauth].js``` in pages and I'm still getting an error.

Specifically, I've copied ```[...nextauth].js``` from the example app and I've imported ```{ getsession }``` in one of my pages.

This whole authorization thing is pretty new to me so what I'm doing wrong might be obvious -- if so, all the better! Thanks for any insight!

Full error:

```Failed to compile.
./node_modules/next-auth/dist/adapters/typeorm/index.js
Module not found: Can't resolve 'mongodb' in 'C:\Users\lazor\Desktop\app\node_modules\next-auth\dist\adapters\typeorm'


> Build error occurred
Error: > Build failed because of webpack errors
    at build (C:\Users\lazor\Desktop\app\node_modules\next\dist\build\index.js:13:913)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-realworld-example-app@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-realworld-example-app@1.0.0 build script.
```

**Comment by iaincollins** [comment]
Hi there!

That's an interesting one.  This actually looks like a problem with build process for that project not handling [dynamic imports](https://nodejs.org/api/esm.html) correctly. I looked at the project and actually can't see what specifically is causing the problem.

**What's going on?**

NextAuth.js doesn't include `mongodb` but if you specify a database connection string (or object) that references MongoDB then it will _conditionally_ import the `mongodb` driver included in the project using a **dynamic import()** . If you have not specified a MongoDB driver it will never try to do this.

This is a legitimate feature of CommonJS and ES modules intended for just this sort of use case.

You should be able to confirm you don't get that error with the [example project](https://github.com/iaincollins/next-auth-example).

_If you are on Windows you may also want to remove `sqlite` as well to make things easier as I appreciate it's a pain to run on Windows; I intend to replace SQLite in the example project to address this._

**Comment by iaincollins** [comment]
Note: I'm sure this is obvious, but if you wanted to make the error go away, you could `mongodb` as a dependancy for now and figure out what is up with the build process there later. :-)

I did actually consider handling this differently in case it cropped up an issue in some setups - even though it's a perfectly legitimate feature…

An alternative way we could handle it is to ask folks to pass in a reference to `mongodb` driver they have loaded instead. This shouldn't really necessary though, as it's a kludge and would mean the method for using a MongoDB database would be different to using an SQL database, would require more code for configuration and would complicate the API and the documentation.

Another alternative approach we could take is trying to fool build systems like this by obfuscating the dynamic import (using a string for the import statement, or wrapping it up somehow) but that's also a kludge for a problem that isn't _our_ problem, and I'd rather only resort to that if it's an especially common problem with a particular framework or platform.

**Comment by iaincollins** [comment]
Closing as #wontfix but feel free to continue discussion!

**Comment by lazordiak** [comment]
Gotcha, thanks for the in-depth explanation!

**Comment by JuanM04** [comment]
@lazordiak , Were you able to solve it without installing `mongodb`?

**Comment by IgorDePaula** [comment]
This and another tricks not work for me.

**Comment by koraysels** [comment]
me neither.. it keeps wnating more and more peerdependencies that arre not needed...

**Comment by balazsorban44** [comment]
soon there will be a dedicated mongodb adapter

https://github.com/nextauthjs/adapters/pull/193
