### ISSUE TITLE
How would I get a unique user id?

### ISSUE THREAD

**Issue by ricjohn-acosta** [iaincollins/next-auth#255]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
How would I get a unique user ID that I can use for fetching user-generated data after user signs in?

**What are you trying to do**
I'm trying to have my users fill up a form after sign in and then display that data in their profile pages what's the best way that I can do this? I've noticed that there's a getUserByProviderAccountId method that I could use is there a way to use this client side?

**Comment by ricjohn-acosta** [comment]
ah sorry, found my answer in the docs. just had to add custom properties to the session object in the the auth options

**Comment by iaincollins** [comment]
Thanks for asking and for coming back with the answer!

I agree this is not very clear for someone coming to the project right now.

This will be improved in #247 - unfortunately what are you doing will probably break soon, but it should be as simple as copying and pasting the code one of the new methods when that happens (and I don't expect it to break again).

Once we have the new system I plan on writing some additional documents / examples / blog posts that take people through how to do things like this.

The ideal method would be to use the `accessKey` in the session (e.g. if it is reading public data, such as fetching posts by a user) or to read from the `Session Token` cookie (which will either be a Session ID or JSON Web Token) in an API route and either look up the User ID or decrypt the JWT to get the data, if the data is not public (e.g. personal information, etc).
