### ISSUE TITLE
Question : Is it possible to directly sign in to a provider (since I'm only using google as sole provider) ?

### ISSUE THREAD

**Issue by x4080** [iaincollins/next-auth#261]
Is it possible to directly sign in to a provider (since I'm only using google as sole provider) ?

signin() always choose multiple providers (which I need only one right now) - so it would be cool if signin([someparameter]) directly go to provider

Thanks

**Comment by iaincollins** [comment]
Sure!

You can do exactly that in the client to create sign in buttons that go straight to a particular authentication provider.

```js
import { signin } from 'next-auth/client'

export default () => <button onClick={() => signin('google')}>Sign in</button>
```

**Comment by x4080** [comment]
Wow, that's very cool, thanks @iaincollins 

BTW i have little suggestions for that multiple button selections, it would be cool if there's logo for each provider button 

And you can close it if you like
