### ISSUE TITLE
How do I get a users AccessToken for an OAuth service?

### ISSUE THREAD

**Issue by chuckstock** [iaincollins/next-auth#270]
**Describe the bug**
After I log in with twitter oAuth there is no accessToken on the user session, so I'm not able to make any further requests to the twitter API.

**To Reproduce**
1. Login through twitter
1. Check the users session and there will not be an access token.
```
export default (req, res) => {
  const session = await getSession({ req })

  if (session) {
    // This will always be undefined with Twitter login.
    const { accessToken } = session.user

  ...
}
```
**Expected behavior**
I would expect there to be an access token to make future requests.

**Comment by laeckerv** [comment]
I was wondering the same thing yesterday. Started using next-auth with the Facebook provider, but the `session` doesn't contain the accessToken

```
import { NextApiRequest, NextApiResponse } from 'next';
import NextAuth from 'next-auth/client';

export default async (req: NextApiRequest, res: NextApiResponse): Promise<void> => {
  const session = await NextAuth.getSession({ req });

  console.log('ApiSession: ', session);

  res.statusCode = 200;
  res.setHeader('Content-Type', 'application/json');
  res.end(JSON.stringify({ name: 'John Doe' }));
};
```

```
ApiSession:  {
  user: {
    name: '...',
    email: '...',
    image: '...'
  },
  expires: '...'
}
```

**Comment by laeckerv** [comment]
Seems like, when we don't use a database and therefore use the JWT the `getSession` doesn't return the `accessToken`.

https://github.com/iaincollins/next-auth/pull/223/files#diff-260a419701f5eb5faf852739254bad14R39

**Comment by iaincollins** [comment]
This has been answered a few times before (please see previous requests) the tl;dr is that NextAuth.js *saves* the `refreshToken` and `accessToken` for each OAuth account so you can do stuff with it if you want to (and it includes a field in the database where you can store the expiry time) but it doesn't currently return handling automatic refreshing of the `accessToken` for you.

You can use the [session callback](https://next-auth.js.org/configuration/callbacks) to return the provider access token from the JSON Web Token (if using JWT) or from the `accounts` table (if you have configured a database).

NextAuth.js returns a session specific `accessToken` if you are using database sessions, so you can build an endpoint that does this as securely as possible. NextAuth.js doesn't expose third party `accessTokens` to the client by default.

**Comment by iaincollins** [comment]
Marking as closed for now. Please do re-open if that was not helpful and there is still a problem.

We'll likely have better documentation for this in a tutorial / guide at some point, as I know it's not obvious right now (it comes up a bunch).
