### ISSUE TITLE
Object is not a function or its return value is not iterable when trying to use "useSession()"

### ISSUE THREAD

**Issue by sadboilogan** [iaincollins/next-auth#271]
I have imported the module using `import { useSession } from 'next-auth/client';` into a file, and when trying to set it up, following the example page on the website.

```js
import { useSession } from 'next-auth/client';

export default () => {
  const [session, loading] = useSession();

  return (
    <div>Hello</div>
  );
};

```

is all im doing right now in `index.js` im guessing im missing some setup or so? i just cant find anything.

**Comment by sadboilogan** [comment]
im dumb, `npm i next-auth` installed an older version than the docs are using

**Comment by iaincollins** [comment]
This is actually confusing as v1 and v2 have some identical exports!

I bet a bunch of folks are running into this right now.

Should resolve itself as a problem when `next-auth@beta` becomes `next-auth@latest` and we retire v1!
