### ISSUE TITLE
Using multiple accounts of the same provider

### ISSUE THREAD

**Issue by nikitalk** [iaincollins/next-auth#275]
**Describe the bug**
Error using multiple accounts of the same provider.

**To Reproduce**
Log in under one account of one provider (for example, Google), log out and log in under another account of the same provider. First account sign-in information will be displayed instead of second account information.

**Expected behavior**
Another account sign-in information should be displayed.

**Comment by iaincollins** [comment]
I can't replicate this issue.

* Are you able to replicate this on https://next-auth-example.now.sh ?
* Can you provide more details about your configuration?
* What does the database look like for both Accounts?

I suspect you might not have been fully logged out when out when you signed in the second time, and so it has joined both accounts to the same User model (so you can use either to sign in as the same User) but looking at the database should confirm that.

**Comment by nikitalk** [comment]
I've added new provider (yandex.ru). 
![image](https://user-images.githubusercontent.com/33490517/84756954-2eb4a000-afcc-11ea-83eb-db8e364b37f0.png)
![image](https://user-images.githubusercontent.com/33490517/84757179-7d623a00-afcc-11ea-976a-6f4c50e09c7a.png)
Sign in with yandex
![image](https://user-images.githubusercontent.com/33490517/84758105-b2bb5780-afcd-11ea-8fc4-c14002c875a4.png)
First account information is shown
![image](https://user-images.githubusercontent.com/33490517/84758199-cff02600-afcd-11ea-95cb-04f01ceaf269.png)
Sign-out
![image](https://user-images.githubusercontent.com/33490517/84757380-bf8b7b80-afcc-11ea-81a5-dbfc0af66063.png)
mongoDB user collection
![image](https://user-images.githubusercontent.com/33490517/84758330-fb731080-afcd-11ea-91a2-1d2b1290d805.png)
mongoDB account collection
![image](https://user-images.githubusercontent.com/33490517/84758438-22314700-afce-11ea-8c53-947a2c5e985c.png)
Sign in with another account
![image](https://user-images.githubusercontent.com/33490517/84758538-41c86f80-afce-11ea-994d-b9fa419ab741.png)
First account information is shown again
![image](https://user-images.githubusercontent.com/33490517/84758621-5efd3e00-afce-11ea-9ebe-558d45d4b625.png)
mongoDB user collection after sign-in with another account
![image](https://user-images.githubusercontent.com/33490517/84758330-fb731080-afcd-11ea-91a2-1d2b1290d805.png)
mongoDB account collection after sign-in with another account
![image](https://user-images.githubusercontent.com/33490517/84758438-22314700-afce-11ea-8c53-947a2c5e985c.png)
There are no new user and account associated with second account.

**Comment by iaincollins** [comment]
Thanks! That's great info and very helpful, though not sure what is going on there.

That's not a built-in provider so can't test it, but from the screenshots it looks like Yandex is returning an Account ID (which I would expect to be unique for each account) so I would expect this to work.

If you define a `signin` callback as an option to NextAuth.js (in `[...nextauth.js]`) you should be able to `console.log()` the contents of the `metadata` object, which should contain the oAuth profile returned by the provider:

```
callbacks: {
  signin: async (profile, account, metadata) => {
    console.log(metadata)
    return Promise.resolve(true)
   }
  }
}
```

More information on that here:
https://next-auth.js.org/configuration/callbacks#signin

It would be helpful to be able to compare the responses (even a redacted view) to get an idea of what might be going on (e.g. is an endpoint returning the same info for two different users somehow?)

**Comment by nikitalk** [comment]
Iain, metadata is correct for every account. 
![image](https://user-images.githubusercontent.com/33490517/84772488-ad690780-afe3-11ea-9ff8-cc1ce75928cc.png)
Most likely something with a database - a separate account is not created for a new user.

**Comment by iaincollins** [comment]
Thanks again, great info! It looks like the provider ID is good but that it's using Client ID instead of the ID for the account in the profile.

Can you check the profile function is returning the right property (e.g. `profile.id` and not `profile.client_id`)?

```
    profile: (profile) => {
      return {
        id: profile.id,
        name: profile.name,
        email: profile.email,
        image: profile.profile_image_url_https.replace(/_normal\.jpg$/, '.jpg')
      }
    },
```

**Comment by nikitalk** [comment]
Oh, it's my fault! I've used `profile.client_id` instead of `profile.id`. I apologize! Now, everything is good!

**Comment by iaincollins** [comment]
Thanks for providing all the info, I'm sure it will be helpful to the next person who runs into the same thing! Would be great if you are able to share the Yandex profile!

**Comment by nikitalk** [comment]
Yes, sure. There it is.
```js
export default (options) => {
  return {
    id: 'yandex',
    name: 'Yandex',
    type: 'oauth',
    version: '2.0',
    scope: 'login:email login:info',
    params: { grant_type: 'authorization_code' },
    accessTokenUrl: 'https://oauth.yandex.ru/token',
    requestTokenUrl: 'https://oauth.yandex.ru/token',
    authorizationUrl: 'https://oauth.yandex.ru/authorize?response_type=code',
    profileUrl: 'https://login.yandex.ru/info?format=json',
    profile: (profile, oAuthProfile) => {
      return {
        id: profile.id,
        name: profile.real_name,
        email: profile.default_email,
        image: null,
      };
    },
    ...options,
  };
};
```

I also want to make profiles for [vk.com](https://vk.com) (the largest Russian social network) and [mail.ru](https://mail.ru) (one of the largest Russian email providers).

**Comment by iaincollins** [comment]
Hey if you work on those, it would be great if you were able to submit them feature requests (or to make a pull request with them!)

**Comment by nikitalk** [comment]
Yes, of course. In the near future I will do a pull request.
