### ISSUE TITLE
With Strapi CMS

### ISSUE THREAD

**Issue by IncomReact** [iaincollins/next-auth#276]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
I would like to know if  I can implement next-auth with Strapi CMS ?

**What are you trying to do**
Strapi give me a token when I receive a success login and I would like to use your system for handle the user session in my next app if its possible..

**Comment by iaincollins** [comment]
I'm not sure! Is it this JSON Web Token you are referring to?

https://strapi.io/documentation/v3.x/guides/jwt-validation.html#customize-the-jwt-validation-function

It should be possible, but the documentation doesn't seem complete as it doesn't show where some of the functions it's calling are coming from, they are not imported in the file (and I'm not clear what platform the example is written for as it's not a Next.js API route).

Your best best would be to ask them, as it's commercial software.

Things that are relevant from NextAuth.js are:

1. The API route that shows how to decode a NextAuth.js JSON Web Token (enabled with `session: { jwt: true }` - probably something you want to do in your case as it's easier than querying the database):

https://github.com/iaincollins/next-auth-example/blob/main/pages/api/jwt-example.js

2. The `jwt: { decode, encode }` options for NextAuth.js where you can define how a JWT is encoded and decoded. By default it is signed and encrypted, but you change this to be whatever you want.

https://next-auth.js.org/configuration/options#jwt

3. You can also use the JWT callback to change what information is stored on the JWT:

https://next-auth.js.org/configuration/callbacks#jwt

I don't know how Strapi works, but they should be able to provide you with some options that allow you to put a working solution together!
