### ISSUE TITLE
Is it possible to use OAuth 1.0a with Twitter?

### ISSUE THREAD

**Issue by shamoons** [iaincollins/next-auth#278]
As per https://stackoverflow.com/questions/62412679/how-can-i-authorize-calls-to-the-twitter-api, it seems I need to somehow use `OAuth 1.0a`. I know that `next-auth` is `Designed to work with any OAuth service, it supports OAuth 1.0, 1.0A and 2.0`, but how do I get it to use the `1.0a`?

**Comment by iaincollins** [comment]
It [already uses OAuth 1.0A](https://github.com/iaincollins/next-auth/blob/main/src/providers/twitter.js).

Please do use the issue templates, they ask questions like "What are you trying to do" and about the documentation and code.
