### ISSUE TITLE
Custom SignIn Page redirects to Signin page again and again

### ISSUE THREAD

**Issue by mmuniyasamy** [iaincollins/next-auth#284]
I am very new to nextjs and next-auth, please help me with my question. I am adding customer signin page in the path: pages/auth/signin. I am able to see the providers already given in [...nextauth].js. Currently i have google and fb providers. When i try to click on signin buttons from my custom page, i am again getting redirected to custom signin page instead of google or fb authentication. 

My SignIn Button code:

```
  <a href="/auth/signin" onClick={(e) => { e.preventDefault(); signin() }}>
            <button className={styles.signinButton}>Sign in</button>
</a>
```

[...nextauth].js settings: 
```
 pages: {
    signin: '/auth/signin',  // Displays signin buttons
  },
```

custom singin.js code:

```
import React from 'react'
import { providers, signin } from 'next-auth/client'

export default ({ providers }) => {
  return (
    <>
      {Object.values(providers).map(provider => (
        <p key={provider.name}>
          <a href={provider.signinUrl} onClick={(e) => e.preventDefault()}>
            <button onClick={() => signin(provider)}>Sign in with {provider.name}</button>
          </a>
        </p>
      ))}
    </>
  )
}

export async function getServerSideProps (context) {
    return {
        props: {
        providers: await providers(context)
        }
    }
}
```

**Comment by iaincollins** [comment]
Looks like you just need slightly different code for your sign in buttons!

The `signin()` function needs to passed the provider ID – e.g. `provider('google')` – rather than the object, which is happening above.

Doing `signin(provider.id)` in the code above should work!

e.g.

```jsx
<a href={provider.signinUrl} onClick={(e) => e.preventDefault()}>
  <button onClick={() => signin(provider.id)}>Sign in with {provider.name}</button>
</a>
```
