### ISSUE TITLE
Gitlab Provider

### ISSUE THREAD

**Issue by SabariVig** [iaincollins/next-auth#285]
**Describe the bug**
+ GitLab As Custom Provider
    + Callback url is not correct 
  
![image](https://user-images.githubusercontent.com/33371586/85106610-1cd03880-b22a-11ea-8d56-1705923f0db4.png)

+ Scope Needs   '+' instead gets replaced by `%2B`

    + And 401 Error
(After I Manually Changed CallbackUrl and scope)

```
[next-auth][error][OAUTH_GET_ACCESS_TOKEN_ERROR] [
  {
    statusCode: 401,
    data: '{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}'
  },
  undefined,
  undefined
] 
https://next-auth.js.org/errors#oauth_get_access_token_error
[next-auth][error][OAUTH_GET_ACCESS_TOKEN_ERROR] [
  {
    statusCode: 401,
    data: '{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}'
  },
  undefined,
  'gitlab',
  '<Token>'
] 
```

**To Reproduce**
https://docs.gitlab.com/ee/api/oauth2.html Docs Found Here

```
    {
      id: 'gitlab',
      name: 'GitLab',
      type: 'oauth',
      version: '2.0',
      scope: 'email+profile+read_user',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://gitlab.com/oauth/token',
      authorizationUrl: 'https://gitlab.com/oauth/authorize?response_type=code',
      profileUrl: 'https://gitlab.com/api/v4/user',
      profile: (profile) => {
        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
          image: "NO"
        }
      },
      clientId: '<Client ID>',
      clientSecret: '<Secret Here>'
    }
```

**Expected behavior**
Work Out Of The Box
+ Callback Should Have Been http://localhost:3000/api/auth/callback/gitlab

**Additional context**
Probably I would have messed up something  .As far as the docs this is the way to do it  

Would like this working and would like to merg to main repo

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ x] Found the documentation helpful
* [ x] Found the example project helpful

**Comment by iaincollins** [comment]
Thanks for the very detailed bug report!

Can you confirm if using separating them with space works for you or not?

`scopes: 'email profile read_user',`

If that doesn't work, can you try passing them as array?

`scopes: ['email', 'profile', 'read_user'],`

_^I was planning to support this but can't remember if it actually works or not._

If neither of these approaches work do let us know!

We might need to do something special for GitLab.

**Comment by SabariVig** [comment]
Yeah the scope was fixed by `scopes: 'email profile read_user'`.But the callback url and 401 error still exists

**Comment by iaincollins** [comment]
The callback URL is `http://localhost:3000/api/auth/callback/gitlab` (as above) is correct.

Why do you think this is incorrect? Are you getting an error telling you that?

**Comment by SabariVig** [comment]
the callback is correct. the error is in the redirect_url in the url picture it . It should have been `https://gitlab.com/oauth/authorize?response_type=code&redirect_uri=http://localhost:3000/api/auth/callback/gitlab`

but it is `https://gitlab.com/oauth/authorize?response_type=code&redirect_uri=%2Fapi%2Fauth%2Fcallback%2Fgitlab`

**Comment by iaincollins** [comment]
Hmm, did you configure the `site` option in NextAuth.js to tell it your site name?

e.g. 

```
site: 'http://localhost:3000`
```

As an option in `/api/auth/[...nextauth.js]`

**Comment by SabariVig** [comment]
:sweat_smile: I cloned the example repo again. i thought my env was being applied.My bad It worked

**Comment by iaincollins** [comment]
Oh great!

This actually puzzled me for a bit as I couldn't figure out why that redirect URI was wrong!

Maybe we should spit out a warning if not configured / make `http://localhost:3000` the default.

Glad it's working!
