### ISSUE TITLE
TypeError: Cannot read property 'csrfToken' of null

### ISSUE THREAD

**Issue by ricjohn-acosta** [iaincollins/next-auth#299]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
Not sure why I'm getting the following error: `TypeError: Cannot read property 'csrfToken' of null` on the client side and `CLIENT_FETCH_ERROR null/csrf TypeError: Only absolute URLs are supported` on the server side. This error only occurs when the browser is recently opened and then navigating directly to /signup page. The error disappears when the index page is loaded first and then navigating to /signup page

**What are you trying to do**
Trying to implement a custom signup page with an email provider and third party providers

**Relevant code**

signup.js
```
import { csrfToken, signin, providers } from "next-auth/client";
import Button from "@material-ui/core/Button";

export default ({ csrfToken, providers }) => {
  return (
    <>
      <form
        method="post"
        action="/api/auth/signin/email"
        onSubmit={(e) => {
          e.preventDefault();
          signin("email", { email: document.getElementById("email").value });
        }}
      >
        <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
        <label>
          Email address
          <input type="text" id="email" name="email" />
        </label>
        <button type="submit">Sign in with Email</button>
      </form>

      {Object.values(providers).map((provider) =>
        provider.name === "Email" ? null : (
          <p key={provider.name}>
            <Button
              href={`/api/auth/signin/${provider.name.toLowerCase()}?callbackUrl=${
                process.env.NODE_ENV !== "production"
                  ? "http://localhost:3000/account-setup"
                  : process.env.SITE
              }`}
            >
              Sign in with {provider.name}
            </Button>
          </p>
        )
      )}
    </>
  );
};

export async function getServerSideProps(context) {
  return {
    props: {
      csrfToken: await csrfToken(context),
      providers: await providers(context),
    },
  };
}
```

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [X] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Thanks for the bug report!

This can happen if you run a function before any cookies are set, it's a bit of an edge case but absolutely needs to be handled more gracefully.

As a work around for now you could calling getCsrfToken server side until we have a solution.

**Comment by iaincollins** [comment]
[I think we have a fix for this!](https://github.com/iaincollins/next-auth/pull/315) If you install `next-auth@2.1.0-beta.0` and try out in PR #315 I would love to know how you get on!

Note:

* This simplifies things so you don't need anything in `next.config.js`.
* The documentation is a draft and the names might be subject to change based on review, but would appreciate any feedback on if the approach works for you.

If you want to see when this change is released, you can keep an eye on that PR.

Depending on how quickly I get feedback and depending on comments in review, if it works for everyone and changes are quick to make it could go live very soon.

**Comment by kbardi** [comment]
It is still happening to me, but it works correctly in dev mode (running `yarn dev`), but in prod it fails (running `yarn build && yarn start`).

I tried with getProviders() and getCsrfToken(), but it didn't work.

Here is the error in console:
```
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/providers',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:22:194)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
] 
https://next-auth.js.org/errors#client_fetch_error
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/csrf',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:22:194)
      at /Users/kevinbardi/Projects1/solosetratadevivir/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
] 
```

is there any workaround for it? If I reload a couple of times the page, it render correctly, which is a weird behaviour.

**Comment by iaincollins** [comment]
It's addressed in v3 which handles configuration slightly differently to resolve this.

The example repo is currently running v3 beta, I'd give that a go. Hopefully will be out soon.

**Comment by iaincollins** [comment]
PS: There is a workaround with setOptions for v2 that I think should be described in the URL linked to from the error

**Comment by kbardi** [comment]
Thank you! It worked! I added in **signin** page `setOptions({ site: process.env.SITE });` and that's it

**Comment by iaincollins** [comment]
I think we are good to close this one! Hopefully with v3 it shouldn't come up. :-)
