### ISSUE TITLE
session() doesn't work well when accessing on iOS

### ISSUE THREAD

**Issue by kazuhideoki** [iaincollins/next-auth#313]
**Describe the bug**
I use session() inside serverSideProps.
But, this error occurs only when accessing on iOS.  Others are OK. - android, macOS.
How should I solve the problem?

```
[next-auth][error][CLIENT_FETCH_ERROR] [
  'null/session',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/home/okikazuhide/salon-tablet/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /home/okikazuhide/salon-tablet/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/home/okikazuhide/salon-tablet/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /home/okikazuhide/salon-tablet/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/home/okikazuhide/salon-tablet/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/home/okikazuhide/salon-tablet/node_modules/next-auth/dist/client/index.js:22:194)
      at /home/okikazuhide/salon-tablet/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
] 
https://next-auth.js.org/errors#client_fetch_error
```

**To Reproduce**
index.tsx
```
export async function getServerSideProps(context:NextPageContext) { 

  const req = context.req
  const session = await session({ req });

  return {
      props: {
        session: session
      },
    };
```

I follow #299 
next.config.js
```
module.exports = {
  env: {
     NEXTAUTH_SITE: "https://example.com",
  },
};
```

[...nextauth].ts options

```
const options = {
  site: "https://example.com",
  providers: [
    Providers.Email({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM,
    }),
    Providers.Credentials({
      authorize: async (credentials) => authorizeCredentials(credentials), // following the document.
      credentials: {
        email: { label: "Email", type: "text ", placeholder: "jsmith" },
        password: { label: "Password", type: "password" },
      },
    }),
  ],
  database: process.env.DATABASE_URL,
  session: {
    jwt: true,
  },
};
```

**Comment by iaincollins** [comment]
Thanks for the detailed bug report and for tying things out and referencing other issues.

This looks like a very similar problem.

I can see where the bug is and will work on pushing out a fix this evening.

**Comment by iaincollins** [comment]
[I think we have a fix for this!](https://github.com/iaincollins/next-auth/pull/315) If you install `next-auth@2.1.0-beta.0` and try out in PR #315 I would love to know how you get on!

Note:

* This simplifies things so you don't need anything in `next.config.js`.
* The documentation is a draft and the names might be subject to change based on review, but would appreciate any feedback on if the approach works for you.

If you want to see when this change is released, you can keep an eye on that PR.

Depending on how quickly I get feedback and depending on comments in review, if it works for everyone and changes are quick to make it could go live very soon.

**Comment by iaincollins** [comment]
I'm going to close this and track the bug report in #299 (just so it's in one place).

Thanks again for the detailed bug report! That's super helpful.
