### ISSUE TITLE
Custom page is not working

### ISSUE THREAD

**Issue by sivaraj-v** [iaincollins/next-auth#322]
Custom page is not working.
https://next-auth.js.org/configuration/pages @iaincollins

**Comment by LoriKarikari** [comment]
Hi, @sivaraj-v can you provide a bit more information? Maybe the error you are seeing or what's not working exactly?

**Comment by iaincollins** [comment]
Please use the issue templates.

We can't help you if you don't give us the information we need to understand the problem and what you have tried already.

**Comment by sivaraj-v** [comment]
![image](https://user-images.githubusercontent.com/6199252/85558774-b2aefd80-b646-11ea-8148-7428aeb61893.png)

I'm getting the following error.

Please find the code in my repo
https://github.com/sivaraj-v/next-auth-example-with-blog

**Comment by sivaraj-v** [comment]
Its closed, so creating new issue 
https://github.com/iaincollins/next-auth/issues/324
