### ISSUE TITLE
Custom Page not working

### ISSUE THREAD

**Issue by sivaraj-v** [iaincollins/next-auth#324]
![image](https://user-images.githubusercontent.com/6199252/85559339-4254ac00-b647-11ea-950f-c263a7050578.png)

I'm getting the following error.

Please find the code in my repo
https://github.com/sivaraj-v/next-auth-example-with-blog

@iaincollins @LoriKarikari

**Comment by iaincollins** [comment]
Please use the issue templates as requested in #322.

The problem is that project is using an old beta release `next-auth 2.0.0-beta.70` and the `_app.js` file isn't setup correctly.

The release version is `next-auth@2.1.0` and [you can find the documentation for _app.js here](https://next-auth.js.org/getting-started/client).

**Comment by sivaraj-v** [comment]
After updating the module, I'm getting the same problem.
https://github.com/sivaraj-v/next-auth-example-with-blog/commit/c27a5bdd6e2dabd9408901e6e5641357b006feec

@iaincollins

**Comment by iaincollins** [comment]
Thanks for the link to the code.

I checked it out and got it working after a couple of changes.

1. Next.js an older version that NextAuth.js isn't compatible with – running `npm install next@latest` fixes that.

2. There are some clashes between the exported function `providers()` and the variable name `providers`.

NextAuth.js also exports the function as `getProviders()` to avoid this.

If you use this instead, it will work:

```js
import React from 'react'
import { getProviders, signin } from 'next-auth/client'

export default ({ providers }) => {
  return (
    <>
      {Object.values(providers).map(provider => (
        <p key={provider.name}>
          <a href={provider.signinUrl} onClick={(e) => e.preventDefault()}>
            <button onClick={() => signin(provider.id)}>Sign in with {provider.name}</button>
          </a>
        </p>
      ))}
    </>
  )
}

export async function getServerSideProps (context) {
  return {
    props: {
      providers: await getProviders()
    }
  }
}
```

**Comment by sebastiancrossa** [comment]
This does not work, either. I have the exact same code set up as above, with `next@^9.4.4` and `next-auth@2.2.0`.

I changed `providers(context)` to `getProviders()` and it didn't solve the issue.

In console I get this error saying `'/api/auth/providers',TypeError: Only absolute URLs are supported`. Would it have something to with the the `pages` options? The setup example on the documentation is different than how it's implemented on the next-auth-example project.

**Comment by robquinn** [comment]
Not working for me either...have tried tons of different versions of `next` and `next-auth`. Something I noticed, the endpoint `/api/auth/providers` is supposed to return the providers in the form of json. If I navigate to it, I get `Internal Server Error`, which is what is causing the issue. But I'm not sure how to fix it. 

The strange thing is, I had all of this working like an hour ago...and then I did something and it stopped working. But I cannot figure out what I changed that caused it to break.

**Comment by robquinn** [comment]
I figured out my issue. in `/pages/api/auth/[...nextauth].tsx`, I had imported `import { useRouter } from 'next/router` and in the body of the file I had called `const router = useRouter()`. Upon removing that, it worked perfectly again!

**Comment by sayinmehmet47** [comment]
has not anyone solved this issue yet? I am using new version of nextjs and typescript. 

```js
import { getProviders, signIn } from "next-auth/react";

export default function SignIn({ providers }) {
  return (
    <>
      {Object.values(providers).map((provider) => (
        <div key={provider.name}>
          <button onClick={() => signIn(provider.id)}>
            Sign in with {provider.name}
          </button>
        </div>
      ))}
    </>
  );
}

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}
any suggestion ??

```

**Comment by laurindo** [comment]
I am having the same issue after deploying to Vercel.
I am using the same code from documentation
`import { getProviders, signIn } from "next-auth/react";

export default function SignIn({ providers }) {
  return (
    <>
      {Object.values(providers).map((provider) => (
        <div key={provider.name}>
          <button onClick={() => signIn(provider.id)}>
            Sign in with {provider.name}
          </button>
        </div>
      ))}
    </>
  );
}

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}`

Object.values(providers).map does not work because "providers" is null;
Does anyone know how to solve it?
My next version: "next": "12"
next-auth: "next-auth": "^4.1.0",

**Comment by Mdb05** [comment]
@laurindo  try this:
{providers && Object.values(providers).map(provider => ())}
