### ISSUE TITLE
Footer on website not showing on first load

### ISSUE THREAD

**Issue by w3bdesign** [iaincollins/next-auth#326]
**Describe the bug**

Parts of the text in the footer on nextjs-auth.js.org is hidden/not showing.

However, refreshing did manage to fix the issue.

Just in case this is an issue that should be looked at, I am opening this issue. Please close this if not relevant.

**To Reproduce**

Go to nextjs-auth.js.org and scroll down to the footer on Firefox. Tested with version 77.0.1 64-bit.

**Expected behavior**

I expect the footer to display properly.

**Screenshots or error logs**

![image](https://user-images.githubusercontent.com/45217974/85629358-0551df00-b672-11ea-9cbe-f7bd39a6d1e9.png)

**Comment by iaincollins** [comment]
Thanks for the bug report!

* I tried regular windows and private browsing windows  and am I'm not able to replicate this in FF 77.0.1 64-bit (Mac)
* It might be the browser being temperamental, I get similar bugs in Safari sometimes.
* We are also using an alpha version of Docusaurus v2 so it might have issues from time to time too.

We can probably ignore this unless more folks have a problem with it.
