### ISSUE TITLE
Customize error sign in page for credentials sign in

### ISSUE THREAD

**Issue by nemmtor** [iaincollins/next-auth#330]
Is there any way to customize sign in page error? I dont want any redirection while signing in.

I want to be able to sign in user without redirecting to sign in page -> it works fine since I used fetch: /api/auth/callback/credentials

The only problem here is when user enters wrong credentials then user is being redirected to error page.

I want to be able to display wrong credentials info right under form itself after fetch is complete.

**Comment by iaincollins** [comment]
There is, it's not especially well documented yet.

Currently you can specify a custom error page, the error code is passed as query parameter in the URL. The error page should to handle all errors though - but you can probably use a catch all for the rest if you are only using credentials based sign in.

There is some (minimal) documentation for the custom pages option here: https://next-auth.js.org/configuration/options#pages

You can see the error codes handled by the default pages here (this really needs to be added to the existing documentation for custom pages): https://github.com/iaincollins/next-auth/blob/main/src/server/pages/error.js

You should be able to catch this redirect in the response if you are handling the submit via JavaScript.

The error page doesn't currently return an HTTP 403 status for this error for `?error=CredentialsSignin` but it probably should as it would make this easier to check for.

**Comment by iaincollins** [comment]
@nemmtor BTW, in case it's not obvious, you can make the error page URL your sign in page URL and parse the query string on it to conditionally show an in-line error on the sign in page. :-)

I have an update that is going to add proper HTTP 403 status codes to the appropriate default error pages, which should also help if not using custom error pages.
