### ISSUE TITLE
Default email sign in link has website in http vs. https

### ISSUE THREAD

**Issue by Romstar** [iaincollins/next-auth#331]
**Describe the bug**
When signing in via email the default HTML template that is sent to the user doesn't utilize https for the website URL but it does utilize https for the sign-in button

**To Reproduce**

1. Create a new next js app
2. Install next-auth
3. setup SMTP
4. perform an email sign in
5. observe that the website URL doesn't utilize https but the sign-in button does. 

Include example code (or link to public repository) which can be used to reproduce the behaviour.

**Expected behavior**
The website URL should match that which is within the SITE environment variable

**Screenshots or error logs**
If applicable, add screenshots or error logs to help explain the problem.

**Additional context**
Obviously not the biggest deal because every user will probably customize the sign-in HTML email

**Comment by iaincollins** [comment]
Oh it should do! Can you take a screenshot to show me and highlight the link that problematic?

I am wondering if this a URL link that the email client is adding. Both Outlook and Apple Mail do that and it's super annoying.

I've actually been working on a new better looking email template that prevents them from doing this by inserting zero width spaces in between dots in the email address and site name.

The new templates look like this:

![Screenshot 2020-06-25 at 17 02 15](https://user-images.githubusercontent.com/595695/85755359-c53c3c00-b705-11ea-9fc6-a89e295b9960.png)

**Comment by Romstar** [comment]
![email_url_no_ssl](https://user-images.githubusercontent.com/2949243/85759616-bbe7ab00-b6d6-11ea-8b04-3720b31837fc.png)

**Comment by iaincollins** [comment]
Thanks! That looks like something that the email client has added, that isn't something NextAuth.js is doing.

The change in #333 should prevent them from doing that (because if nothing else, it's confusing for users).
