### ISSUE TITLE
Example with getSession() in _app.js?

### ISSUE THREAD

**Issue by theogravity** [iaincollins/next-auth#345]
**Your question**

All the examples I've seen for `getSession()` is for a specific page, but I'd like to pass the `session` prop at the layout level, via `_app.js`.

What is the proper way of using it in `_app.js` for both client/server side application?

**What are you trying to do**

Apply the `session` prop to all page props without duplicating logic by setting it through `_app.js`.

```
// _app.tsx
// some psuedo-code
import { Provider } from 'react-redux'
import { getSession, Provider as AuthProvider } from 'next-auth/client'

const WrappedApp: FC<CustomProps> & StaticComponents = (props) => {
  const { Component, pageProps, session } = props

  return (
    <Provider store={store}>
      <AuthProvider session={session} options={{ site: 'http://localhost:3000' }}>
            <HeaderNav {...props} />
            <Component {...pageProps} />
      </AuthProvider>
    </Provider>
  )
}

// https://github.com/isaachinman/next-i18next/issues/615
WrappedApp.getInitialProps = async (context) => {
  const appProps = await App.getInitialProps(context)
  const session = await getSession(context)
 
  // ----------> returns null
  console.log(session)

  return {
    ...appProps,
    session
  }
}

export default WrappedApp
```

With the example, I also get despite having the proper `site` value:

```
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/session',
  TypeError: Only absolute URLs are supported
```

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
I agree, I think this a thing it would be helpful to have a tutorial for. This is tricky as the Provider isn't initialised yet so doesn't help if you want to call `getSession()` from `getInitialProps()` in `_app.js`.

There is an undocumented work around, where you can export and call `setOptions()` directly  from next-auth/client, as in the example below, which should solve this problem.

```js
import { Provider } from 'react-redux'
import { setOptions, getSession, Provider as AuthProvider } from 'next-auth/client'
setOptions({ site: 'http://localhost:3000 })

const WrappedApp: FC<CustomProps> & StaticComponents = (props) => {
  const { Component, pageProps, session } = props

  return (
    <Provider store={store}>
      <AuthProvider session={session} options={{ site: 'http://localhost:3000' }}>
            <HeaderNav {...props} />
            <Component {...pageProps} />
      </AuthProvider>
    </Provider>
  )
}

WrappedApp.getInitialProps = async (context) => {
  const appProps = await App.getInitialProps(context)
  const session = await getSession(context)

  return {
    ...appProps,
    session
  }
}

export default WrappedApp
```

Note: You can pass a regular environment variable (e.g. `process.env.SITE`) and it will be picked up here.

**Comment by theogravity** [comment]
Thanks for the response. I no longer get the fetch error, but the `session` value still comes out as `null`. I've verified that I do have an active session as `useSession()` will work on the client side.

**Comment by theogravity** [comment]
I think I see where the problem is, and I believe it's a bug in the client code when dealing when doing the following:

```js
// https://github.com/isaachinman/next-i18next/issues/615
WrappedApp.getInitialProps = async (context) => {
  const appProps = await App.getInitialProps(context)
  const session = await getSession(context)

  return {
    ...appProps,
    session,
  }
}
```

I put some log statements in `dist/client/index.js`:

```js
var getSession = function () {
  var _ref = _asyncToGenerator(function* () {
    var {
      req
    } = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

    var baseUrl = _baseUrl();

    var options = req ? {
      headers: {
        cookie: req.headers.cookie
      }
    } : {};

    console.log(arguments)
    console.log('req', req)
    console.log('opts', options)
    console.log(baseUrl, "/session")
```

The output looks like this:

```
[Arguments] {
  '0': {
    AppTree: [Function: AppTree],
    Component: [Function: IndexPage] { getNavbarContent: [Function] },
    router: ServerRouter {
      route: '/',
      pathname: '/',
      query: {},
      asPath: '/',
      basePath: '',
      events: undefined,
      isFallback: false
    },
    ctx: {
      err: undefined,
      req: [IncomingMessage],
      res: [ServerResponse],
      pathname: '/',
      query: {},
      asPath: '/',
      AppTree: [Function: AppTree]
    }
  }
}
req undefined
opts {}
http://localhost:3000/api/auth /session
```

`req` is undefined because it's looking for it directly under `arguments[0]` when it's actually under `arguments[0].ctx.req` in this case

**Comment by iaincollins** [comment]
> Another question - how do folks generally implement getSession() in a reusable way? Is calling the method on every page the thing to do in next when you have common init/fetch logic across pages?

The best approach is to use the `useSession()` hook, as it will share the session object between components (and even between page navigations) and avoids constantly calling the server.

If you need server side rendering then yes, you need to call `getSession()` on every page view.

You can do that by creating an 'AuthPage' class and extending it (or a HOC and using that) to apply it only to pages that require authentication, or add it to `_app.js` as you've done here, if all pages on your site require authentication with server side rendering.

We plan to do some tutorial for folks in future to help with this.

Thanks for you PR will leave a note there!

**Comment by theogravity** [comment]
I went with this route because useSession would have this brief flash where the page renders in a logout state then immediately flashes the layout to the login one, which was pretty jarring.

**Comment by iaincollins** [comment]
The [example project](https://next-auth-example.now.sh) doesn't have that problem and was created to show how to avoid that, including on sites that also need to support server side rendering on some pages.

If you go this route, do aware your website will be slower to access as a result and Next.js will generate a warning if you do this because it prevents automatic static optimization of your site.

The performance impact isn't usually noticeable running locally as everything runs very quickly, but can be significant when the site is deployed to Vercel / AWS Lambda.

Related: I've added some examples of alternative approaches to securing routes in #347 that contain approaches that are somewhat relevant.

**Comment by theogravity** [comment]
Thank you so much for your time and providing guidance. I'll check out your updated examples.

**Comment by iaincollins** [comment]
I'm happy to leave this issue open until we have a more satisfying answer to your question. :-)

**Comment by talentlessguy** [comment]
@iaincollins 

> I agree, I think this a thing it would be helpful to have a tutorial for. This is tricky as the Provider isn't initialised yet so doesn't help if you want to call `getSession()` from `getInitialProps()` in `_app.js`.
> 
> There is an undocumented work around, where you can export and call `setOptions()` directly from next-auth/client, as in the example below, which should solve this problem.
> 
> ```js
> import { Provider } from 'react-redux'
> import { setOptions, getSession, Provider as AuthProvider } from 'next-auth/client'
> setOptions({ site: 'http://localhost:3000 })
> 
> const WrappedApp: FC<CustomProps> & StaticComponents = (props) => {
>   const { Component, pageProps, session } = props
> 
>   return (
>     <Provider store={store}>
>       <AuthProvider session={session} options={{ site: 'http://localhost:3000' }}>
>             <HeaderNav {...props} />
>             <Component {...pageProps} />
>       </AuthProvider>
>     </Provider>
>   )
> }
> 
> WrappedApp.getInitialProps = async (context) => {
>   const appProps = await App.getInitialProps(context)
>   const session = await getSession(context)
> 
>   return {
>     ...appProps,
>     session
>   }
> }
> 
> export default WrappedApp
> ```
> 
> Note: You can pass a regular environment variable (e.g. `process.env.SITE`) and pass it as the value for the `site` option.

I have something similar:

```tsx
import React from 'react'
import { AppProps } from 'next/app'
import { ThemeProvider } from '@chakra-ui/core'
import { Provider as AuthProvider, setOptions } from 'next-auth/client'
import theme from 'lib/theme'

setOptions({ site: 'http://localhost:3000' })

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <ThemeProvider theme={theme}>
      <AuthProvider options={{ site: 'http://localhost:3000' }}>
        <Component {...pageProps} />
      </AuthProvider>
    </ThemeProvider>
  )
}

export default App
```

But I still get the error about fetch in `api/*` routes, like here:

```ts
import { getSession } from 'next-auth/client'
import { NextApiRequest, NextApiResponse } from 'next'

export default (req: NextApiRequest, res: NextApiResponse) => {
  console.log(getSession())
  res.end('hi')
}
```

**Comment by erhankaradeniz** [comment]
I know this issue is closed, but would it be possible to pass crsfToken on _app too? (i'm asking because I have a few pages where I check if a user is logged in or not after a certain action, e.g. click on a button).

For this I'm fetching the session and csrfToken on pageload or on the server. It would be nice if we could pass those down, so we don't need to check on those pages.. (this means I'd be able to have those pages be SSG instead of SSR).

**Comment by erhankaradeniz** [comment]
As a side note, I'm fetching those since after the click. I'm showing a login modal, where I need to pass the csrf for email login.

**Comment by Robert-OP** [comment]
Similar problem here trying to `getSession` in `App.getInitialProps` as below and pass the `pageProps.session` in the `AuthProvider` as in the examples above (and next-auth's documentation). To be noted that I have the session when I use the client-side hook `useSession()`, but not when I try to `getSession(ctx)` in `App.getInitialProps`, neither in `getServerSideProps` function on another page (basically getting the same error as below).

So, it works well when I work with in local development, but when I deploy it to `Azure` in a `Docker` container I get the following error:

```
2021-02-18T12:08:04.140106140Z [next-auth][error][client_fetch_error]
2021-02-18T12:08:04.140215540Z https://next-auth.js.org/errors#client_fetch_error https://beta.femaleinvest.com/api/auth/session FetchError: invalid json response body at https://beta.femaleinvest.com/api/auth/session reason: Unexpected token ﻿ in JSON at position 0
2021-02-18T12:08:04.140224040Z at /usr/next_app/node_modules/node-fetch/lib/index.js:272:32
2021-02-18T12:08:04.140239040Z at runMicrotasks (<anonymous>)
2021-02-18T12:08:04.140252040Z at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

```
App.getInitialProps = async ({ Component, ctx, router }: AppContext) => {
  const localeFilter = { name: 'locale', value: router.locale.replace('-', '_') };

  const footerData = await getStrapiSingle('footers', { filter: localeFilter });
  const headerData = await getStrapiSingle('headers', { filter: localeFilter });
  const session = await getSession(ctx);

  let pageProps = {};

  if (Component.getInitialProps) {
    pageProps = await Component.getInitialProps(ctx);
  }

  let editorMode = process.env.EDITOR_MODE === 'true';

  return {
    pageProps: { ...pageProps, headerData, footerData, editorMode },
  };
};
```

**Comment by neongreen** [comment]
For anyone looking for an example, here's mine:

```typescript
import type { AppContext } from 'next/app'
import App from 'next/app'
import Layout from '../components/layout'
import { getSession, SessionProvider } from "next-auth/react"
import SSRProvider from 'react-bootstrap/SSRProvider'
import { SWRConfig } from 'swr'

function MyApp({ Component, pageProps, session }) {
  return (
    <SSRProvider>
      <SessionProvider session={session}>
        <SWRConfig
          value={{
            refreshInterval: 3000,
            fetcher: async (resource, init) => fetch(resource, init).then(async res => res.json())
          }}
        >
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </SWRConfig>
      </SessionProvider>
    </SSRProvider>
  )
}

MyApp.getInitialProps = async (appContext: AppContext) => {
  const session = await getSession({ req: appContext.ctx.req })
  const appProps = await App.getInitialProps(appContext)
  return { ...appProps, session }
}

export default MyApp
```

Now I can use `const {data: session} = useSession()` in my React components, including the layout component, and everything works without flashes of "logged out" on page visits/refreshes.

**Comment by balazsorban44** [comment]
Keep in mind that `getInitialProps` will deoptimize the whole site. I would recommend something like this:

```jsx
export default function App({Component, pageProps: {session, ...pageProps}}) {
  return (
    <SessionProvider session={session}>
      <Layout>
        <Component {...pageProps} />
      </Layout
    </SessionProvider>
  )
}

function Layout({ children }) {
  const session = useSession()
  if (session.status === "loading") {
    return "skeleton UI"
  } else if(session.status === "unauthenticated") {
    return "not logged in"
  }
  return "UI using session.data"
}
```

With a nicely implemented skeleton UI, you can minimize/eliminate the most undesired flashes/jumps. This will have a better perceived performance in my opinion.

**Comment by neongreen** [comment]
There's a button in the header that says "log in" or "log out". I'm not sure what you mean by skeleton UI but off the top of my head I don't know how the flash there could be hidden.

FWIW my site is a note-taking app and the only page that could even in theory be pre-rendered is the landing page, everything else is generated from user content.

**Comment by balazsorban44** [comment]
I see. Dashboards/user-focused sites are generally a good exception for this. 

[Skeleton UI](https://blog.logrocket.com/improve-ux-in-react-apps-by-showing-skeleton-ui/#:~:text=A%20skeleton%20screen%20is%20a,shape%20similar%20to%20actual%20content.&text=In%20addition%20to%20skeleton%20screens,content%20loaders%2C%20and%20ghost%20elements.)

**Comment by aidanCQ** [comment]
For those that are experiencing a flash of content when using a client side redirect this may help:

```ts
const AuthRedirect = ({ children }: { children?: React.ReactNode }) => {
  const { status } = useSession();
  const router = useRouter();
  React.useEffect(() => {
    if (status === "unauthenticated" && router.asPath !== "/auth/signIn") {
      signIn();
    }
  }, [status, router]);
  // Make sure that you show a loading state for BOTH loading and unauthenticated. This is because when status becomes `unathenticated` the component renders, returns children and then the useEffect redirect is fired afterwards, hence the temporary flash of the child content.
  if (status === "loading" || status === "unauthenticated") {
    return <div>Loading...</div>
  }
  return <>{children}</>;
};
```
