### ISSUE TITLE
Open signin in new tab

### ISSUE THREAD

**Issue by MehediH** [iaincollins/next-auth#360]
Hey! Is it possible to serve the `signin()` method on a new tab? So for example, if a user clicks on a button, is there any option that would allow the sign-in link to open in a new tab?

I am trying to directly trigger a sign-in via Twitter with `signin("twitter")` which means it does not go through `api/auth/signin` and was wondering if it is possible to open the Twitter auth link on a new tab instead of the current page as I would like to preserve some of the app's local context which isn't stored anywhere.

Thanks!

**Comment by iaincollins** [comment]
This is not currently a feature.

You can write your own logic to do this and use a custom redirect function to handle directing to a URL that syncs the session state and closes the popup window after sign in.

We might expose this as an option in future.
