### ISSUE TITLE
How can I register users with email and password?

### ISSUE THREAD

**Issue by dhuber666** [iaincollins/next-auth#361]
Hiho,

I read the whole documentation and also the part with the "Credentials" Provider. It seems that it's the thing I need but it doesn't get persisted in the database according to the docs. 
There is also an email provider, but I don't want it that way (email gets sent to the user and then he can register). I want a pretty normal and boring email + password signup, is this possible?

Is there really no way to add a normal email / password provider or am I missing something? I think that's still the most common way to signup to web apps todate. 

BTW: I love this library everything works just out of the box. Now I only need email / password besides facebook and google signup

Appreciate your help 👍

**Comment by iaincollins** [comment]
You can do this [with the credentials provider](https://next-auth.js.org/providers/credentials).

It is not a path we go out of our way to support as it's less secure than passwordless mechanisms (and often less convenient for users) but if you have an existing database of usernames and passwords it's possible.
