### ISSUE TITLE
Minor typo in the docs

### ISSUE THREAD

**Issue by ryanbahan** [iaincollins/next-auth#365]
**Describe the bug**
A clear and concise description of what the defect is.

Not sure if this is the right place - sorry if not! Minor typo on email page: [https://next-auth.js.org/providers/email](https://next-auth.js.org/providers/email)

Second paragraph of **How it works** reads _"If someone provides the email address of an existing account when **signin** in"_ instead of **signing in**

**Comment by ryanbahan** [comment]
Another one on [https://next-auth.js.org/configuration/pages](https://next-auth.js.org/configuration/pages)

Second paragraph of **Email sign in page**

_This is easier of if you use the build in signin() function, as it sets the CSRF automatically._

Should read: 

_This is easier if you use the build in signin() function, as it sets the CSRF automatically._

**Comment by iaincollins** [comment]
Thanks! Have fixed both of these.

PS: Feel free to raise tiny PRs for docs using the "Edit this page" on GitHub to suggest corrects if you like!
