### ISSUE TITLE
vercel, google account redirect is not correct

### ISSUE THREAD

**Issue by x4080** [iaincollins/next-auth#369]
Hi, I know this sounds strange 

I'm trying auth with vercel with google account, using next auth version :
```
"next-auth": "^2.2.0",
```

When trying to login, google shows error page showing redirect is not correct with address : 
```
https://[projectname].vercel.app//api/auth/callback/google 
```

there is // (two /) before api and to fix it I must change in google credentials to that address instead of regular

```
https://[projectname].vercel.app/api/auth/callback/google 
```

But I think with localhost works correctly

Hope it helps

**Comment by iaincollins** [comment]
Hi, what did you set your site name as?

It seems like you have a slash at the end of it.

**Comment by iaincollins** [comment]
Closing this issue as it is a bug in app configuration. The example project shows how to use sign in with Google and is hosted on Vercel. 

Please use the issue templates, as they are intended to help with issues like this, and include links to documentation and the working example project.

In future we may add a regex to the URL to handle conditional auto-prefixing and strip slashes as appropriate to reduce the number of issues being raised that are down to configuration problems.

**Comment by x4080** [comment]
@iaincollins You're correct, my mistake
