### ISSUE TITLE
OAuth sign in page fail

### ISSUE THREAD

**Issue by mhinostroza** [iaincollins/next-auth#377]
I try create un page signin but not working

```
import React from 'react'
import { providers, signin } from 'next-auth/client'

export default ({ providers }) => {

  return (
    <>
      {Object.values(providers).map(provider => (
        <p key={provider.name}>
          <a href={provider.signinUrl} onClick={(e) => e.preventDefault()}>
            <button onClick={() => signin(provider.id)}>Sign in with {provider.name}</button>
          </a>
        </p>
      ))}
    </>
  )
}

export async function getServerSideProps (context) {
  return {
    props: {
      providers: await providers(context)
    }
  }
}
```

I'm used this example  https://github.com/vercel/next.js/tree/canary/examples/with-next-auth

This is errors response

![image](https://user-images.githubusercontent.com/9615129/86259219-605b6880-bb81-11ea-969c-2e05eb1fe3b1.png)

**Comment by iaincollins** [comment]
Hi there! Please stay tuned for an update and some tutorials on how to create and use custom pages. We've had a lot of questions about custom pages and are making some changes to this in an upcoming release to address this.
