### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by lavcraft** [iaincollins/next-auth#382]
**Summary of proposed feature**
I'm using next-auth with next-with-typescript bootstrap example. Now it's non comfortable, because require additional typings
![image](https://user-images.githubusercontent.com/576422/86347069-75f68e00-bc66-11ea-98ea-86a07228ec5a.png)

**Purpose of proposed feature**
Simplify integration process with @types dependency - @types/next-auth

**Comment by LoriKarikari** [comment]
TypeScript support is being worked on. You can check out #220.

**Comment by lluia** [comment]
Re-opening this, as the **above PR, #220, is stale**, the actual work is carried on 🔜 **DefinitivelyTyped**:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45775

I'm going to close #220 so people don't get confused and comment the code there, hopefully instead commenting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45775 by following this comment 🤙🏽🤞🏽
