### ISSUE TITLE
Cannot use getCsrfToken with getStaticProps

### ISSUE THREAD

**Issue by erhankaradeniz** [iaincollins/next-auth#383]
I'm facing an issue when I'm trying to deploy to preview that is the same as this [one](https://github.com/iaincollins/next-auth/pull/315)

However when I change the method to getServerSideProps everything works fine. (is there any way that I cannot seem to find in the documentation to get this working with getStaticProps? or is this not something that is planned?

**Comment by iaincollins** [comment]
The [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) method in Next.js is only for build time page generation (e.g. for generating static pages from a headless CMS) and cannot be used for user specific data such as sessions or CSRF Tokens.
