### ISSUE TITLE
API protection example in Docs

### ISSUE THREAD

**Issue by lavcraft** [iaincollins/next-auth#386]
I have next-auth.session with jwt token. How to populate next api route with authentication information?
I'm reading docs and not understand clearly how to protect next API

*Solution*
Add to docs and example secured API endpoint (like [protected.js](https://github.com/iaincollins/next-auth-example/blob/main/pages/protected.js), but for API)

**Comment by iaincollins** [comment]
There is [already an example of how to do this in the example project](https://github.com/iaincollins/next-auth-example/blob/main/pages/api/jwt-example.js).

In v3 you can also use getSession() in API routes, the same way you can in server side pages.

e.g. `const session = await getSession({req})`

Please use the issue templates, they are there to help!

**Comment by bscaspar** [comment]
It looks like the example Ian linked moved to [here](https://github.com/iaincollins/next-auth-example/blob/328556866527411073d8634d8f54f147a6a04490/pages/api/jwt-example.js)

**Comment by iaincollins** [comment]
Thanks for updating the link! To add to that, there are now [examples that show how to access a token and session](https://github.com/iaincollins/next-auth-example/tree/main/pages/api/examples) from an API route in v3.

The might be updated again before release of v3 with a new recommended approach for accessing a JWT token, but the example usage from v2 should remain valid even if the recommended approach changes slightly.
