### ISSUE TITLE
Snap LoginKit Web Integration

### ISSUE THREAD

**Issue by peartobear** [iaincollins/next-auth#388]
**Summary**

Integrating Snap LoginKit for Web using serverless code to handle res/resp [Snap LoginKit Web](https://snapkit.com/docs/login-kit-web)

**Purpose of proposed feature**
SnapChat is a popular platform with 223m daily active users. Snap's auth flow is hence an important feature for next-auth

**Comment by LoriKarikari** [comment]
I have a WIP provider for Snapchat. Will try to add it tomorrow 👍

**Comment by LoriKarikari** [comment]
@peartobear Snapchat requires [PKCE](https://www.oauth.com/oauth2-servers/pkce/) which we currently don't support so I wasn't able to create that provider yet. This is something we will implement in the future but isn't a big priority right now.

**Comment by peartobear** [comment]
@LoriKarikari Thank you! Unrelated ques but is there any way to integrate Snap's loginkit in nextjs app without setting up a custom express server as described in their [docs](https://docs.snapchat.com/docs/login-kit-web)?

**Comment by LoriKarikari** [comment]
Yeah, I think you can convert the HTML examples on that page to React JSX and it should work.
