### ISSUE TITLE
Logout of Keycloak not working, session seems to be persisted. And having trouble debugging the logout flow

### ISSUE THREAD

**Issue by phillystafford** [iaincollins/next-auth#40]
Hi @iaincollins, Firstly, great library. Thanks for the effort you put into it :)

I'm having a bit of trouble trying to figure out an issue. I know you're not affiliated with the [`keycloak-passport`](https://github.com/exlinc/keycloak-passport) strategy that I'm using but I'm hoping your experience might be able to point me in the right direction.

My issue is related to the issue @garmeeh [was having last week](https://github.com/iaincollins/next-auth/issues/39)

I'd like to use [keycloak.org](https://www.keycloak.org/) as authentication on my project and I'm using your [`nextjs-starter`](https://github.com/iaincollins/nextjs-starter) examples to test the flow of login and log out. I'm also leveraging the [`keycloak-passport`](https://github.com/exlinc/keycloak-passport) to handle the [keycloak.org](https://www.keycloak.org/) actions.

I've tested logging in and out using Google as an identity provider and it worked flawlessly so I'm doing something wrong with [keycloak.org](https://www.keycloak.org/) but I'm not sure what.

When I run your examples locally I can successfully log in using the [`keycloak-passport`](https://github.com/exlinc/keycloak-passport) strategy but when I logout, the client side says I'm logged out and when I try to log in again using [`keycloak-passport`](https://github.com/exlinc/keycloak-passport) I get the `Unable to sign in` page. 
![image](https://user-images.githubusercontent.com/3513149/44368297-4a32ea80-a4ca-11e8-8f22-2633b8d3cdbd.png)

It seems to be logging out from the client side but the session seems to be persisted on the server side. When I hit my login page directly it redirects me to the account admin section on my keycloak instance so I'm definitely still logged in on the server.

I've tried to debug the logout flow to see if I can determine the problem but none of the `console.log` statements I placed in the `handleSignOutSubmit()` and `signout()` functions are firing.

I also opened an issue on the [`keycloak-passport`](https://github.com/exlinc/keycloak-passport) library, which can be found [here](https://github.com/exlinc/keycloak-passport/issues/2), in the hopes that someone can help me with this issue. 

Any help with this issue would be greatly appreciated

**Comment by iaincollins** [comment]
Hi, I saw the comment in https://github.com/exlinc/keycloak-passport/issues/2.

If someone wants to send me credentials for a public (e.g. dev/test) instance of Keycloak (e.g. a server URL, client id / secret and a username and password for the service) I'm happy to investigate and try and come up with a strategy that works (and/or fix any bugs that are specific to compatibility with Keycloak). I expect we can solve it and include it as one of the example strategies.

I'll keep the details confidential and would probably only need them for ~24 hours. I'd need them to be on a service on the internet without a proxy / VPN  – but as is just for debugging purposes, it doesn't need to be SSL and running on a weird port would be fine.

If anyone is able to do this, you can email details to me at me@iaincollins.com and I'll take a look.

Thanks!

**Comment by aol-nnov** [comment]
Iain, I've just sent you a mail with keycloak config, if it's still relevant.

**Comment by iaincollins** [comment]
Thank you, I'll take a look over the net 24-48 hours and will post an update tomorrow!

**Comment by LoriKarikari** [comment]
v2 is out now and doesn't use passport.js anymore.
