### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Levino** [iaincollins/next-auth#418]
Thank you @iaincollins for [insulting me](https://github.com/iaincollins/next-auth/issues/417#issuecomment-656713242) and then locking the conversation so I cannot complain. Nice touch!

I know that "if one uses your code and the http methods and the cookie settings etc. etc. in the correct way this is safe". I just try to reduce the number of "if"s in my code. This was not an intent to discredit your setup or this package or your knowledge about security. It is just hard to do authentication securely (remember all the ifs!) and not all of the users of your package are as brilliant as you are. See me...

**Comment by iaincollins** [comment]
This is a place for people who have specific questions about NextAuth.js or or want to contribute via code, bug reports or to suggest enhancements.  It is not a general purpose forum or blog where people are invited to discuss whatever topic they want.

Please respect the time of the people volunteering on this project and use the issue templates provided if you have a question.
