### ISSUE TITLE
Correct redirect url for Facebook OAuth deployed to Vercel?

### ISSUE THREAD

**Issue by bscaspar** [iaincollins/next-auth#422]
Not sure this is the right place to ask this but I figured I'd give it a go incase anyone here has experienced something similar:

I use Facebook as my provider. This works no problem when deployed locally. After deploying the app to Vercel, upon signin Facebook returns the following error "Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

The request to Facebook clearly has `redirect_uri={my-app-vercel-url}%2Fapi%2Fauth%2Fcallback%2Ffacebook` in the url, so I included `{my-app-vercel-url}-api-auth-callback-facebook` in the App Domains in the Facebook app settings, along with `vercel.app` and `{my-app-vercel-url}.vercel.app`, all with no luck.

Am I missing something?

**Comment by iaincollins** [comment]
This might related to #423 but in case not the API endpoint `/api/auth/providers` returns a list of each configured provider, and includes callbackUrls for each provider (based on your current site URL).

e.g. https://next-auth-example.now.sh/api/auth/providers returns:

```json
{
  "email": {
    "id": "email",
    "name": "Email",
    "type": "email",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/email",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/email"
  },
  "apple": {
    "id": "apple",
    "name": "Apple",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/apple",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/apple"
  },
  "auth0": {
    "id": "auth0",
    "name": "Auth0",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/auth0",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/auth0"
  },
  "facebook": {
    "id": "facebook",
    "name": "Facebook",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/facebook",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/facebook"
  },
  "github": {
    "id": "github",
    "name": "GitHub",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/github",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/github"
  },
  "google": {
    "id": "google",
    "name": "Google",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/google",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/google"
  },
  "twitter": {
    "id": "twitter",
    "name": "Twitter",
    "type": "oauth",
    "signinUrl": "https://next-auth-example.now.sh/api/auth/signin/twitter",
    "callbackUrl": "https://next-auth-example.now.sh/api/auth/callback/twitter"
  }
}
```

PS: Facebook is slightly awkward to get started with as it requires a whole separate list of credentials to use with localhost URLs. If you are looking for one that is easy to test with, Twitter's implementation is a bit simpler and a less hassle.

**Comment by bscaspar** [comment]
This was indeed related to #423, thanks for the follow up!
