### ISSUE TITLE
Using signin when deployed on Vercel repeats the base site url twice in call to api/auth/signin 

### ISSUE THREAD

**Issue by bscaspar** [iaincollins/next-auth#423]
This seems a bit odd and perhaps is a Vercel bug - I'll be following up with them as well. 

My options are configured like so: 
```js
const options = {
  site: process.env.NEXT_PUBLIC_SITE ?? 'http://localhost:3000',
  providers: [
    Providers.Facebook({
      clientId: process.env.FB_CLIENT_ID,
      clientSecret: process.env.FB_CLIENT_SECRET,
      scope:
        'email instagram_basic instagram_manage_insights user_location user_link user_hometown user_gender user_friends user_birthday user_age_range',
    }),
  ],
  secret: process.env.NEXT_AUTH_SECRET,
  session: {
    jwt: true,
  },
```

This runs locally just fine using both `yarn dev` and `vercel dev`. When I deploy to a Vercel preview environment, and make sure to set the NEXT_PUBLIC_SITE preview environment variable to the preview site URL, when `signin` is called, I'm redirected to `https://{my-preview-site}.vercel.app/{my-preview-site}.vercel.app/api/auth/signin`. (note that the base url repeats)

This still happens even if I hardcode the Vercel url like `site: 'https://{my-preview-site}.vercel.app',` or (I don't think these would work anyway, just testing) `site: '/'` or ` site: 'http://localhost:3000'`.

It also happens if I remove `site` completely from the `options` in `[...nextauth].ts` and just include it in the `AuthProvider` like this: 
```js
<AuthProvider
  options={{
    site: '{my-preview-site}.vercel.app',
  }}
  session={session}
>
```

The component to call sign in is a simple button: 
```js
<Button
  className={classes.button}
  variant='contained'
  color='primary'
  type='submit'
  onClick={signin}
>
  Sign in
</Button>
```

**Oddly, the error doesn't happen if I do this:**
```js
<AuthProvider
  options={{
    site: 'http://localhost:3000',
  }}
  session={session}
>
```
Then
- Deploy to Vercel
- Run the site locally so that localhost:3000 is available
- Navigate to the Vercel deployment site at `https://{my-preview-site}.vercel.app/`
- Hit the Sign In button and it redirects to `http://localhost:3000/login?callbackUrl=http://localhost:3000` as expected

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by bscaspar** [comment]
Perhaps related to https://github.com/vercel/next.js/pull/14804

**Comment by bscaspar** [comment]
48 hours later and cooler heads have prevailed. The url I was using for the Vercel site did not include https, and therefore must have been interpreted as a route.

**Comment by iaincollins** [comment]
No worries, thanks for updating! We've seen this before but wasn't certain it was the same issue.

Version 3.0 includes changes to prevent this from being an issue.
