### ISSUE TITLE
after build got this error pages/api/auth/signin/google.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by alsemanynet** [iaincollins/next-auth#427]
I got this error after build 
pages/api/auth/signin/google.js net::ERR_ABORTED 404
but i dev mode everything works great 
anyone know why this happened ? 
I'm using 
pages/api/auth/[...nextauth].js

**Comment by iaincollins** [comment]
Hi, we don't have enough information to be able to help with this request.

Could you re-submit, using the provided issue templates and including any relevant configuration?

**Comment by iaincollins** [comment]
PS: If this is your first time using NextAuth.js, you might want to try [cloning the example project](https://github.com/iaincollins/next-auth-example) and configuring that to get started (as simple was we try to make it, it's still unfortunately a little complicated to get started).
