### ISSUE TITLE
Not playing nicely with an https nginx proxy in front of a dockerized nextjs container

### ISSUE THREAD

**Issue by awcoding** [iaincollins/next-auth#431]
**Describe the bug**
Everything worked good locally but badly on deploy. Using the example template - setting both `NEXTAUTH_URL` and  `<Provider options={{ site: 'https://mydomain.tld' }} >` to mydomain.tld is causing me problems on the next-auth parts of our website. The rest of the next.js site from the same project is working fine. Also seems a bit unclear why both are config properties. It might be clearer to have one or the other. Eg. using getStaticProps or getStaticPaths for the client side hydration. 

**To Reproduce**
Create a Dockerfile that loads example project and have nginx proxy to it:

info  - Loaded env from /opt/app/.env.local
app_1  | ready - started server on http://localhost:3000
app_1  | [next-auth][error][client_fetch_error] [
app_1  |   'https://mydomain.tld/api/auth/session',
app_1  |   FetchError: invalid json response body at https://mydomain.tld/api/auth/session reason: Unexpected token < in JSON at position 0
app_1  |       at /opt/app/node_modules/next/dist/compiled/node-fetch/index.js:1:133590
app_1  |       at processTicksAndRejections (internal/process/task_queues.js:93:5) {
app_1  |     type: 'invalid-json'
app_1  |   }
app_1  | ] 
app_1  | https://next-auth.js.org/errors#client_fetch_error

Include example code (or link to public repository) which can be used to reproduce the behaviour.

I've altered the site name to mydomain.tld for this bug report. The next-auth parts of the site are virtually identical to the next-auth-example project.

**Expected behavior**
Everything runs good.

**Additional context**
Tested with both https://mydomain.tld and https://mydomain.tld/api/auth. 
Grepping the next-auth source it looks like there are some references to env vars. Perhaps the bug is somehow related? I propose that only the example project should read environmental vars and not the next-auth lib itself. 

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ x] Found the documentation helpful
* [ x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by LoriKarikari** [comment]
hi, @awcoding did yo find a solution for this? Are you willing to share if for future reference?

**Comment by awcoding** [comment]
@LoriKarikari Sorry there was a typo in the Dockerfile that copied the api folder into site root instead of pages/. Most of the website is static content so I didn't notice. The error was due to the api lookup reading the default 404 html page @ api/.

**Comment by dendisuhubdy** [comment]
@awcoding @LoriKarikari I happen to have the exact same problem at this moment, I'm trying @awcoding's solution to `@LoriKarikari Sorry there was a typo in the Dockerfile that copied the api folder into site root instead of pages/. Most of the website is static content so I didn't notice and filed this bug a little too quickly. The error was due to the api lookup reading the default 404 html page @ api/.`

**Comment by vasilenka** [comment]
@dendisuhubdy did you find a solution to your problem?
I happen to have the exact same problem too

**Comment by dendisuhubdy** [comment]
@vasilenka yes I did, follow the next auth's dockerfile solved the problem and also putting the NEXT_AUTH site on the dockerfile solved the problem

**Comment by dendisuhubdy** [comment]
@vasilenka yes I did, follow the next auth's dockerfile solved the problem and also putting the NEXT_AUTH site on the dockerfile solved the problem

**Comment by vasilenka** [comment]
Alright, I'm putting it here just in case someone runs into this trouble again.
This is how I solved my error:

1. Make sure you set the `NEXTAUTH_URL` env properly
2. This error happened in the `callbacks` section of your config. So, check if you have any code that modifies the value of each `callbacks` on `[...nextauth].js` file. If you did modify some value, try to remove/comment on the modified code first. In my case, one function that I run in my callback didn't have a proper error handler and it caused the error.
