### ISSUE TITLE
Github Provider: Ensure both profile.name and profile.login is present in the session object

### ISSUE THREAD

**Issue by styxlab** [iaincollins/next-auth#446]
Github profiles must have a unique "profile.id" and a unique "profile.login". Both "profile.name" and "profile.email" can be null and are not necessarily unique. 

In PR #424 I made a quick fix to use "profile.login" as a fallback, in case "profile.name" is null. However, this also means that the unique "profile.login" information is lost henever a user fills out the name.

I propose to use "profile.login" as the user name in all cases, but attach the Github "profile.name" as an additional field, as that info is important too. The user within the session object should have both informations available.

In addition, "profile.id" should also be available in the session object, currently there are only the following fields available:
```
{
  user: {
    name: 'styxlab',
    email: null,
    image: 'https://avatars1.githubusercontent.com/u/19638263?v=4'
  },
  expires: '2020-08-18T21:36:29.310Z'
}
```
Which means there is no single unique field in that object.

This is a proposal and care should be taken that this works also with the other providers, which may not differentiate between a login and a user name.

**Comment by iaincollins** [comment]
Hi there! If this is dome

**Comment by iaincollins** [comment]
Hi there! I'm going to ask if you want to submit this that you use the template provided as requested. This is really important to understand what you want out of this and how you would use it.

Adding the 'username' and/or 'id' for every service a user account is associated with is not something it makes sense to return in every session object (or JWT). A dedicated API endpoint should be used for that (and is already something in development).

We _might_ want to start storing account metadata at some point, but that would only happen if and when we implement Access Token rotation.
