### ISSUE TITLE
Prisma Adapter "updateSession" Unknown arg `userId`

### ISSUE THREAD

**Issue by tylangesmith** [iaincollins/next-auth#450]
**Describe the bug**

Hey peeps, been trying out the v3 branch for a few days now and keep coming across this issue, absolutely love the work you's are doing and super keen to use this in production soon!

This bug relates to the `updateSession` handler trying to update all properties on the `session` object instead of explicitly updating the `expires` property similar to the issue described in this [comment](https://github.com/iaincollins/next-auth/issues/384#issuecomment-660640360). 

**Screenshots or error logs**

```javascript
[next-auth][error][update_session_error] PrismaClientValidationError:
Invalid `prisma[Session].update()` invocation in
/xxx/xxx/xxx/xxx/node_modules/next-auth/dist/adapters/prisma/index.js:376:36

  372   id
  373 } = session,
  374     rest = _objectWithoutProperties(session, ["id"]);
  375
→ 376 return prisma[Session].update({
        where: {
          id: '034cb2bc-6f30-4827-aa2e-5de8a80ccfe0'
        },
        data: {
          userId: '93da02ca-d57e-4675-89c5-e4391e40af09',
          ~~~~~~
          accessToken: 'ckcr9johe0004yhjtn61k5zt6',
          sessionToken: 'ckcr9johe0003yhjtru62hgbf',
          accessTokenExpires: null,
          expires: new Date('2020-08-19T09:53:06.894Z'),
          createdAt: new Date('2020-07-18T06:21:31.442Z'),
          updatedAt: new Date('2020-07-18T06:21:31.442Z')
        }
      })

Unknown arg `userId` in data.userId for type SessionUpdateInput. Did you mean `user`? Available args:
type SessionUpdateInput {
  id?: String
  accessToken?: String
  sessionToken?: String
  accessTokenExpires?: DateTime
  expires?: DateTime
  createdAt?: DateTime
  updatedAt?: DateTime
  user?: UserUpdateOneRequiredWithoutSessionsInput
}
```

**Comment by iaincollins** [comment]
As of `next-auth@3.0.0-beta.20` the Prisma support should work pretty well now. The [v3 beta documentation](https://next-auth-docs-git-v3.iaincollins.vercel.app/configuration/databases) has been improved and includes full SQL schemas for MySQL and Postgres you copy and paste to get started.
