### ISSUE TITLE
Can't npm install example site

### ISSUE THREAD

**Issue by webbygregg** [iaincollins/next-auth#46]
I tried an npm install on the example folder here and received a no such file or directory, rename on .staging\next-auth.... error

**Comment by iaincollins** [comment]
Hi sorry for the delay, I'm not sure what's causing this.

Can you tell me what Operating System you are using (e.g. Windows, Mac, Linux distro)  and what version of npm you have (`npm -v`) .

**Comment by digitallyamar** [comment]
I see same issue with my setup on Ubuntu 16.04 64-bit machine with npm v5.6.0.

**Comment by techbitconti** [comment]
FYI - I had a same issue on Ubuntu 16.04 64-bit machine with npm v5.6.0, and I fixed it by running 
_npm update_

**Comment by iaincollins** [comment]
Things should be fine now in 1.12.1. Note that at least Node 8.x and npm 6.x are recommended.
