### ISSUE TITLE
Typescript Types?

### ISSUE THREAD

**Issue by NickBolles** [iaincollins/next-auth#47]
Are there any typescript typings or any plans to make them?

If not I might whip some up.

**Comment by iaincollins** [comment]
There are not, but this would be very welcome.

If you could provide an example (even if it's just a set of instructions here!) of how to check they work and are correct to make maintain easier that would be great!

**Comment by NickBolles** [comment]
Sounds good. I'll submit a PR an a bit. 

I don't know of any good way to check that they work with a JavaScript project besides manually looking over them. But they just need to be updated whenever a module, function or object signature changes.

**Comment by falleco** [comment]
Hey! I tried to use the TS types you provided, but found some problems using it in my projects.
I created #71 to apply the changes I needed, and also provided a typescript example.

As I am no typescript pro, criticism is welcome.

**Comment by iaincollins** [comment]
Being tracked in #220

**Comment by lluia** [comment]
Yup just the last part of publishing the types missing, I'll try to give it a push 🙏🏻
