### ISSUE TITLE
CouchDB Support

### ISSUE THREAD

**Issue by mqtik** [iaincollins/next-auth#471]
Hi.

Since this library provides out the box MongoDB support, is there any plans to include CouchDB?

Like pouchdb-authentication

**Comment by iaincollins** [comment]
[Please use the issue templates when creating a new issue.](https://github.com/iaincollins/next-auth/issues/419)

There are no immediate plans to support CouchDB.

It's not supported by TypeORM or Prisma, so it would need it's own adapter.
