### ISSUE TITLE
Strapi provider for login functionality

### ISSUE THREAD

**Issue by mbudak** [iaincollins/next-auth#474]
It is really good to see if you support Strapi login. Strapi is a nice and clean API and if you support a provider it really helps some of the developers.

**Comment by iaincollins** [comment]
_Please use the issue template when requesting an enhancement._

We've had people ask about Strapi before (#276).

As far as I know, Strapi is not an authentication provider (e.g. it doesn't have an API OAuth clients can consume).

For any folks that would like an example of how to use Strapi and NextAuth.js together (which I think would be a great idea) I suggest asking the folks at Strapi to ask them about providing an example of how to use their product with NextAuth.js.

I'm happy to help with that if anyone from Strapi wants to get in touch!
