### ISSUE TITLE
Prisma Adapter: Unknown arg `user` in data.user for type SessionCreateInput

### ISSUE THREAD

**Issue by firede** [iaincollins/next-auth#477]
**Describe the bug**

Got `PrismaClientValidationError` when I click the login link in the email.

**To Reproduce**

- version: `3.0.0-beta.20`
- provider: Email
- adapter: Prisma
- database: postgres
- sql schemas: <https://next-auth-docs-git-v3.iaincollins.vercel.app/schemas/postgres>

**Screenshots or error logs**
```js
[next-auth][error][callback_email_error] PrismaClientValidationError:
Invalid `prisma[Session].create()` invocation in
/{APP_ROOT}/node_modules/next-auth/dist/adapters/prisma/index.js:294:36

  290   dateExpires.setTime(dateExpires.getTime() + sessionMaxAge);
  291   expires = dateExpires.toISOString();
  292 }
  293
→ 294 return prisma[Session].create({
        data: {
          expires: '2020-08-24T07:24:07.532Z',
          user: {
          ~~~~
            connect: {
              id: 1
            }
          },
      +   userId: Int,
      +   sessionToken: String,
      +   accessToken: String,
      ?   createdAt?: DateTime,
      ?   updatedAt?: DateTime
        }
      })

Unknown arg `user` in data.user for type SessionCreateInput. Did you mean `userId`?
Argument userId for data.userId is missing.
Argument sessionToken for data.sessionToken is missing.
Argument accessToken for data.accessToken is missing.

Note: Lines with + are required, lines with ? are optional.
```

**Additional context**

`dist` and `src` looks different.

`3.0.0-beta.20` dist:

`/node_modules/next-auth/dist/adapters/prisma/index.js` L294-L303:
```js
            return prisma[Session].create({
              data: {
                expires,
                [User]: {
                  connect: {
                    id: user.id
                  }
                }
              }
            });
```
`v3` src:
https://github.com/iaincollins/next-auth/blob/442a3047a3fefda0601441eff5e2f2f701f0898c/src/adapters/prisma/index.js#L164-L171

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found [documentation](https://next-auth-docs-git-v3.iaincollins.vercel.app/errors) but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
@firede Thanks for a great bug report! I really appreciate it when they are this good.

Yikes! It looks like that last beta build was screwy!

I've just fixed that by rebuilding and releasing a new update, if you update to `3.0.0-beta.21` the issue should be resolved!

Not sure why/how this happened. The release process for beta builds isn't automated yet (something we should look at) and somehow the dist dir had a stale version of this file, which should never happen as the built step is triggered pre-publish. o.O

**Comment by iaincollins** [comment]
Let me know if you have any problems with it!

**Comment by firede** [comment]
Thanks, it works! 👍

![CleanShot 2020-07-25 at 18 51 54@2x](https://user-images.githubusercontent.com/157338/88455472-1c216680-cea8-11ea-9f40-b1f1f305afe7.png)

...but `email_verified` field is empty, not sure if it is a bug or by design.

**Comment by iaincollins** [comment]
Thanks for the feedback!

RE: `email_verified` - it's by design, I think we need to document that somewhere!

The `email_verified` is only updated when a user verifies by signing in with email (if the email provider is configured), when they do it records the timestamp of when it was verified. You can also use this column if you have your own email verification system. Currently there is no way to trigger a 'verify your address' messages, so it is only populated when singing in via email.

Some providers (e.g. Google) do return a a similar value, but it varies a lot between providers so we don't use OAuth provider provided details for this.

**Comment by firede** [comment]
When I using email provider, input email address, click the `Sign in` link in the email, `email_verified` is `NULL`, but actually the email has been verified 🤔

Now it's ran to:

https://github.com/iaincollins/next-auth/blob/40cb62f187f4ffd1d85bdc61e67394e4639f0b50/src/server/lib/callback-handler.js#L91-L96

When I sign out and sign in again, `email_verified` updated:

<img width="222" alt="CleanShot 2020-07-25 at 20 06 32@2x" src="https://user-images.githubusercontent.com/157338/88456699-6b6c9480-ceb2-11ea-961d-1c13b606a537.png">

https://github.com/iaincollins/next-auth/blob/40cb62f187f4ffd1d85bdc61e67394e4639f0b50/src/server/lib/callback-handler.js#L86-L90

**Comment by iaincollins** [comment]
Thanks for the report! I've published a quick hotfix that should address this (3.0.0-beta.22).

I haven't had time to test it, but will do later.

**Comment by iamartisan** [comment]
Hi I also replicated this with this error
Error Name: '**UpdateUserError**'

Version: "next-auth": "4.0.0-beta.2",
Adapter: "@next-auth/prisma-adapter": "0.5.2-next.5"

Logs
![Selection_005](https://user-images.githubusercontent.com/49083784/134774623-cfdde6c0-7e9b-4882-b452-fa573100f461.png)

And also got this build logs
![Selection_007](https://user-images.githubusercontent.com/49083784/134774646-1964cd7b-6d41-4ee4-8923-3095e57e3013.png)

if i install different version of prisma adapter, my next-auth version automatically turns to version 4.0.0
What version must i install to ger rid this compatibility issue?

aside from that that, all functionalities are working.

Thanks Team.
