### ISSUE TITLE
Getting [next-auth][error][adapter_connection_error] QueryFailedError: constraint "PK_." of relation "users" does not exist

### ISSUE THREAD

**Issue by ghoshnirmalya** [iaincollins/next-auth#479]
**Describe the bug**
I'm using NextAuth with Hasura and I'm getting the following error:

```
[next-auth][error][adapter_connection_error] QueryFailedError: constraint "PK_a3ffb1c0c8416b9fc6f907b7433" of relation "users" does not exist
```

**To Reproduce**
Please checkout [the code after this commit](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/tree/10699ec8144ab91831adf338d09e8ab1a96dae9a) since the changes are in a PR.

The links to the necessary parts of the code:
1. [Link to nextauth.ts](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/10699ec8144ab91831adf338d09e8ab1a96dae9a/frontend/pages/api/auth/%5B...nextauth%5D.ts)
2. [Link to all migration files](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/tree/10699ec8144ab91831adf338d09e8ab1a96dae9a/backend/migrations)

Include example code (or link to public repository) which can be used to reproduce the behaviour.

**Expected behavior**
The error shouldn't appear.

**Screenshots or error logs**
<img width="1415" alt="Screenshot 2020-07-26 at 11 43 22 AM" src="https://user-images.githubusercontent.com/6391763/88472876-3f462780-cf35-11ea-93e3-938a4cf58bca.png">

**Additional context**
1. NextAuth version: **3.0.0-beta.19**
2. NextAuth Provider(s) that I'm using: [Email](https://next-auth.js.org/providers/email)
3. Database URL: **DATABASE_URL="postgres://username:password@some-string.amazonaws.com:5432/some-other-string?ssl=true&synchronize=true"**

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ghoshnirmalya** [comment]
If I remove `&synchronize=true`then the above error goes away and the login page (`/api/auth/signin`) works. However, after clicking on the link sent to the email, I get the following error:

```
[next-auth][error][create_user_error] QueryFailedError: null value in column "name" violates not-null constraint
```

**Screenshots**
<img width="1592" alt="Screenshot 2020-07-26 at 11 48 54 AM" src="https://user-images.githubusercontent.com/6391763/88472945-0e1a2700-cf36-11ea-8bbd-adbd7e3e031d.png">

**Comment by ghoshnirmalya** [comment]
This issue was happening on Heroku. After creating a new project from scratch in Heroku, this issue doesn't exist anymore. I'll reopen this issue if it happens again.

**Comment by LoriKarikari** [comment]
@ghoshnirmalya yeah, you should only use synchronize locally.
