### ISSUE TITLE
Pass provider to jwt callback

### ISSUE THREAD

**Issue by janus-reith** [iaincollins/next-auth#482]
**Summary of proposed feature**
The callback for the `jwt` payload should have access to provider details.

**Purpose of proposed feature**
While I currently have access to the default `token` object and `OAuthProfile`with an excerpt of data from the provider,
I have no way to determine which provider was used.
I want the JWT to include the name of the used provider for further usage. 

**Detail about proposed feature**
I guess this could be done easily by adding `provider` as an additional argument to `callbacks.jwt` here:
https://github.com/iaincollins/next-auth/blob/3202ca1037e2e72ccc49cfd9e0d92922d5f0eda1/src/server/routes/callback.js#L73

Furthermore, the `user`, `profile` and `account` could also be passed(I assume at least one the three would be redundant, but didn't check the purpose of each). There might be usecases where it is interesting to store the access token or profile id as part of the jwt.

**Comment by iaincollins** [comment]
Hi there! This is already in progress and recently dropped in the current beta.

The [latest documentation should cover everything](https://next-auth-docs-git-v3.iaincollins.vercel.app/configuration/callbacks). v3 will probably be live very soon.

**Comment by janus-reith** [comment]
@iaincollins Great! Although looking at the code, `provider` seems to not be included, is that part of the user or account object?

**Comment by iaincollins** [comment]
Yeah! Sorry I know it's not super obvious without some examples (there are still some gaps in tutorials) but the 'account' object contains the Provider ID (e.g. 'twitter'), Provider Account ID (e.g. '1234567') the provider type (e.g. 'oauth') and the Refresh Token and Access Token.

The profile object contains the actual raw OAuth Profile (name, location, username, etc.) for that provider.

The contents vary for non-OAuth providers (Email, Credentials) but are very similar and have logical substitutes.

**Comment by janus-reith** [comment]
@iaincollins Thanks, sounds like this exactly covers my neeeds.
