### ISSUE TITLE
Allow returning more explicit error text when sign in fails

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#49]
We should try and return more detailed error information when sign in fails, perhaps by passing an additional query string parameter to the ./auth/error page with a detailed error.

We should allow the `signIn()` method to throw an Error object and serialise it in the query string.

The copy on the example oauth error page could probably use another pass as well, to see if it can be shorter. It should probably have an email sign in option on the page.

See #45 for details.

**Comment by adeshkumar1201** [comment]
Is this enhancement done?

**Comment by iaincollins** [comment]
This is resolved in v2 beta
