### ISSUE TITLE
WP Rest API as Provider

### ISSUE THREAD

**Issue by aristech** [iaincollins/next-auth#53]
Is it possible to add wordpress rest api as provider?

Instead of mongo db i'd like to use wp. I have a project where i get the user data and but i want to make the auth persistent.

**Comment by jenssogaard** [comment]
Hi @aristech. You sure could rewrite the datalayer and make API requests to WordPress that takes care of create/update/login. I assume you want to use something like [Passport-Wordpress](http://www.passportjs.org/packages/passport-wordpress/) to allow WP users to authenticate? 

I can't really see this being a sustainable or smart path to go down.

**Comment by aristech** [comment]
Hi @jenssogaard, thanks for the reply,
I managed the authentication by creating and storing nonce as cookie along with the id and using that each time for crud.

**Comment by iaincollins** [comment]
Sorry it took a while to respond! Thanks for coming back and for updating the issue (and to @jenssogaard for offering help).
