### ISSUE TITLE
next.js 7.0.2

### ISSUE THREAD

**Issue by saintego** [iaincollins/next-auth#56]
Hi,
I updated nextjs from 5 to 7 and callbacks from Google, or email links are not working. Google send me to error page, while query is null, even it is `http://localhost:3000/auth/error?action=signin&type=oauth&service=Google`. Email link show just blank page on `http://localhost:3000/auth/callback?action=signin&service=email` 
Is it working with next 7?

**Comment by saintego** [comment]
I had wrong configuration at _app.js

**Comment by iaincollins** [comment]
Thanks for the update! The example now uses Next.js 7.0.2 so is a more up to date reference.
