### ISSUE TITLE
Add example to secure some urls

### ISSUE THREAD

**Issue by mping** [iaincollins/next-auth#57]
How should one go about securing some urls? I'm guessing if one requires authentication, it means we want to protect about unauthenticated parties.

Ideally, when rendering server-side, if a url is protected it should be redirected to an auth page `/auth`, and when calling a protected api from browser, the server should return some error.

I would be happy to submit a PR for docs/code/whatever, just need some pointers.

**Comment by iaincollins** [comment]
That would be super welcome!

An example page in `examples/pages/` and some documentation seems like it might be helpful.

**Comment by mping** [comment]
@iaincollins  Currently this is what I have, using a custom server. It's kinda working but I'd like to ensure all the API calls that go to the server proxy have a handler to redirect to `/auth` on the client side if the request is not authenticated. Do you have any pointers?

```
const expressApp = express();
const port = process.env.PORT || 3000;

expressApp.use(bodyParser.json());
expressApp.use(bodyParser.urlencoded({ extended: true }));
expressApp.use('/api/', proxy(options));
expressApp.use('/static', express.static('static'))

const dev = process.env.NODE_ENV !== 'production'
const nextApp = next({ dev })
const handleWithNext = nextApp.getRequestHandler()


nextApp.prepare()
  .then(() => {
    // Load configuration and return config object
    return nextAuthConfig()
  })
  .then(nextAuthOptions => {
    // Pass Next.js App instance and NextAuth options to NextAuth
    return nextAuth(nextApp,  Object.assign(nextAuthOptions, {expressApp: expressApp}))
  })
  .then((response) => {
    //register interceptor AFTER next-auth but BEFORE next nextApp
    expressApp.use(function (req,res,next) {
      //assuming /auth is the authentication base url (/auth/google, etc)
      if (!req.isAuthenticated() && req.url !== '/auth' && !req.url.startsWith('/static')) {
        return res.redirect('/auth')
      }
      return handleWithNext(req, res)
    });


    expressApp.listen(port, () => console.log(`Listening on port ${port}`));
    console.log(`Ready on http://localhost:${port}`)
  })
  .catch(err => {
    console.log('An error occurred, unable to start the server')
    console.log(err)
  })
```

**Comment by parth298** [comment]
That would be super welcome!

An example page in examples/pages/ and some documentation seems like it might be helpful.<a href="https://letsgetstartaffiliate.com/work-from-home-jobs/" rel="dofollow">work from home jobs</a>

**Comment by iaincollins** [comment]
This is now covered in the version 2 documentation.
