### ISSUE TITLE
Unable to login through passport strategy if local account exists.

### ISSUE THREAD

**Issue by drudv** [iaincollins/next-auth#61]
Assume we have a local account for `user@server.com` email. All attempts to sign in using external identity providers (through a passport strategy) that have `user@server.com` as email in profile info are rejected because of this line:

https://github.com/iaincollins/next-auth/blob/61eedb26b0d447ddba497f8c141947878c981f52/src/passport-strategies.js#L237

It's probably reasonable (according to the comment before this line), but IMHO instead of just rejecting successful sign-in in this case, it's better to redirect to another page with a prompt to enter user's passport to confirm the intent.

If it makes sense, I would try to prepare a PR to resolve it this way (or probably the other way you might suggest) since it's a blocker for me.

**Comment by drudv** [comment]
Also I think we could resolve it by marking some identity providers as safe (`false` by default), to prevent such situation. I understand that there some strategies (like OpenID) that allows users to make their own OpenID server to forge other users' identity, but if we are talking about trusted centralized identity providers like GitHub, we can safely let a user to sign-in through them even if there is the local account for the same email, right?

**Comment by drudv** [comment]
@iaincollins Could you please take a look at PR #64?

Looks like redirecting to a confirmation page with a password input would require a temporary state to keep profile data received from external identity provider in order to use the data for creating an account after the intent confirmation.

So I ended up sticking with the second option we were talking about: `trustedIdentity` property in provider config.

**Comment by iaincollins** [comment]
Oh that's great thanks, will comment on the PR!

**Comment by iaincollins** [comment]
PR #64 is now merged but not rolled out in a new version on NPM yet. I'd like to update the template pages and documentation, and ideally get some automated testing in place in the next few days before we do that.
