### ISSUE TITLE
Update README to thank contributors

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#65]
Reminder to update the README to thank recent PR contributors and to reflect the enhancements they have added to the next release (hopefully out this week).

**Comment by needcaffeine** [comment]
Hi-- I just stumbled onto this project and am now working on implementing it into my application. Just wanted to check if I should wait for this next release you speak of.

Thank you!

**Comment by LoriKarikari** [comment]
Contributors are now added to the website.
