### ISSUE TITLE
Usage with Laravel Passport

### ISSUE THREAD

**Issue by vojthor** [iaincollins/next-auth#67]
Hi Ian,
at first, awesome library!
Not sure if I missing something obvious or being just plain stupid. I'm trying to figure out auth with Laravel Password endpoint (https://laravel.com/docs/5.7/passport).
On Laravel side it's working all good - I can send e-mail + password, I get bearer token and I can use it for "protected" stuff. 
So I'm thinking, all I need is to create custom password strategy somehow or it's more i need?

Thanks in advance!
Vojta

**Comment by vojthor** [comment]
So... I can't get past this error in callback, any ideas?
```
TypeError: Cannot set property 'accessToken' of undefined
    at functions.find.then.user (/Users/vojthor/Sites/vindecoder-nextjs/node_modules/next-auth/src/passport-strategies.js:205:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by irvv17** [comment]
Did you resolve this?
