### ISSUE TITLE
Getting error when running "next export". TypeError: req.linked is not a function

### ISSUE THREAD

**Issue by Naterra** [iaincollins/next-auth#68]
![image](https://user-images.githubusercontent.com/8204364/50468202-85f82800-0974-11e9-90fd-400249ad629f.png)

**Comment by nickmcmillan** [comment]
I'm having the same issue. 

I believe it's originating from `next-auth-client.js`, namely the functions `linked` and `providers` which seem to handle the destructured `req` argument differently depending on client vs server. 

But beyond that I'm not sure how to fix it.

**Comment by mitkodkn** [comment]
Any progress on solving the issue? I have it, too.

**Comment by williamnvk** [comment]
I have the same problem.
```Unhandled Rejection (TypeError): req.linked is not a function```

**Comment by albertincx** [comment]
@Naterra 
You must understand that this is static HTML.
Module will not work

If you decide to export the site, you can do so

`static async getInitialProps({req, res, query}) {
      req.providers = () => {
      }
      req.linked = () => {
      }`
...optional
`props.providers = await NextAuth.providers({req}) || {}`

**Comment by iaincollins** [comment]
Sorry to read a lot of folks ran into this and I'm not sure why - it seems like a bug in NextAuth 1.x but I've never run into it for some reason.

Closing this off as finally [resolved by upcoming release of 2.0](#99).
