### ISSUE TITLE
Add method for deleting an account

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/next-auth#7]
To promote the practice of providing an easy way for users to delete their accounts, which all sites should provide, NextAuth should provide a POST endpoint to allow users to delete their account.

Note: The example project currently includes a `remove(id)` method, but next-auth does not currently add a route that can be called to invoke it (e.g. `/auth/delete`).

**Comment by LoriKarikari** [comment]
New issue targeting this for newer release #228
