### ISSUE TITLE
Use next-auth with decoupled API?

### ISSUE THREAD

**Issue by jimmiejackson414** [iaincollins/next-auth#70]
Hi there, wonderful library!

Apologies if this isn't a great place for this question, however I've pored over articles/SO/tutorials for awhile now and thought I'd give it a shot here!

I was wondering if you had any suggestions on implementing Next-Auth with a decoupled API. In my repo I've got an 'api' folder which contains my Rails API for handling user authentication, but I know this library uses Express/Passport for user authentication. On my frontend I'm using Next.js and modeled my login after [this repo](https://github.com/jimmylee/next-postgres).

Thank you!

**Comment by ntgussoni** [comment]
I'm in the same situation, I wonder if there's a workaround

**Comment by jimmiejackson414** [comment]
@ntgussoni I'd been looking at that but was scared off with how it's setup with MongoDB currently. Maybe I'll give it a shot with connecting it to my Postgres app. Mind sharing if you come up with something?

**Comment by iaincollins** [comment]
Hi there! Thank you, sorry I wasn't able to reply in a timely way.

Hopefully this should be addressed with [announcement of version 2.0](#99) which no longer uses Express or Passport.js and will support multiple databases out of the box, if you have need of the package again.
