### ISSUE TITLE
Q: Wonder how it works

### ISSUE THREAD

**Issue by RuizhenMai** [iaincollins/next-auth#72]
Sorry this is not an issue. I tried to use req.user to check if it's logged in with a stateful backend api. But when a page get rendered by server and by client, it generates different result because the server gives backend and frontend different cookie. When I use browser to log in, I can only have a valid req.user on the client rendered page. How does this module solve it? Thanks for any help

**Comment by iaincollins** [comment]
Sorry I left this so long to reply to.

This shouldn't happen, but it's been so long I can't really help.

Hope you found a solution! :-)
