### ISSUE TITLE
Documentation issue with Separate Apps

### ISSUE THREAD

**Issue by ScottAgirs** [iaincollins/next-auth#77]
Cannot find documentation anywhere on how to implement `next-auth` with backend/frontend being separated - ie - two different apps each on its own domain.

Assuming that the [example app index.js](https://github.com/iaincollins/next-auth/blob/master/example/index.js) file includes parts from both - Frontend ( nextJS ) dependencies **_and_** backend, it is unclear how to implement this into NextJS app, where NodeJS backend is on a separate server

Many thanks in advance

**Comment by alisonconley** [comment]
I have run into the same issue, did you find a solution?

**Comment by iaincollins** [comment]
I appreciate this is an an old issue, so any advice I give now probably isn't that helpful.

It is possible with both v1 and v2 - and I have used v1 that way on some sites - but it's slightly tricky if they are on separate URLs / domains, as it's very easy to make makes in configuration - meaning it can be to get working without also introducing a new security vulnerability.

I think this will be simpler with v2, although as Next.js now has the `/api` route, I think that's how most folk will consume it and less people will have to worry about this.

However, for folks with multiple sites on different subdomains this will still be possible via the new `allowCallbackUrl` and `cookies` configuration options, which allow all aspects (including cookie domains and cookie names + prefixes, and cookie options) to be customised.

**Comment by yevon** [comment]
Did you find any solutions for this? As it is quite common and I cannot find the way to make it to work, all the oauth request callback urls are pointing to the backend instead of the frontend and I don't know how to fix this.
