### ISSUE TITLE
Question: Adding attributes to props.session.user

### ISSUE THREAD

**Issue by stelian87** [iaincollins/next-auth#78]
Hello,

I was asking this in a closed topic but i don't know how visible it is.
I wonder what is the best approach to getting some information about the user from a 3rd party web api and injecting it in the current user. insert a fetch in the insert function?
insert: (user, oAuthProfile)...

i.e. i'd like to implement roles and authorization. and i'd like to keep the role in the same session.

**Comment by iaincollins** [comment]
Moving this into milestone 2.0 as a reminder to document this. Relates to #81

**Comment by iaincollins** [comment]
This is now covered in version 2 documentation for the `sesson.get` option.
