### ISSUE TITLE
Creating a user process

### ISSUE THREAD

**Issue by Naterra** [iaincollins/next-auth#81]
I see the insert() method in functions.js but cant see the place where it used. At same time the library creating users somewhere... It is completely wrong approach, because we have to do much more  before user record could be saved in DB. In my case, I have to assign a role before that happen. How it could be implemented?

**Comment by iaincollins** [comment]
Thanks for the question, and sorry for late response (which isn't that helpful now I'm sure).

I don't have an example yet, but the new [version 2.0](#99) incorporates feedback on this and should make this sort of situation easier to cater for.

I'll leave this issue open until I get round to have some examples / documentation of how to do this in 2.0.

**Comment by iaincollins** [comment]
Moving this into 2.0 milestone as a reminder to document how to do this.

**Comment by iaincollins** [comment]
Bumping this into 2.1.

It's something I'd like to support, probably via a simple async function so you can do as many operations as you like before creating a user account, but I don't think it's going to make the cut for the 2.0 release this month.

**Comment by iaincollins** [comment]
This is now covered in the documentation for the `session.get` function in version 2
