### ISSUE TITLE
Importing next-auth/client gets regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by richardkeller411** [iaincollins/next-auth#83]
import NextAuth from "next-auth/client";    

I've tried adding in import "regenerator-runtime/runtime"; 

 Tried .babelrc

{
  "presets": ["next/babel"],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}

**Comment by woowebsite** [comment]
I also have same problem

**Comment by iaincollins** [comment]
Hi folks, sorry to read you ran into this.

Appreciate it's been a while between updates, but [version 2.0](#99) should be out soon.

This has been useful feedback. A few folks ran into similar problems. With that in mind, the new version has less shenanigans and should be a lot easier to integrate and this isn't won't exist, so going to mark this as closed for now.

There probably won't be a fix for 1.x users, but the new version should be out in a few weeks.
