### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by Babbz75** [iaincollins/next-auth#86]
I'm running into an issue with a dependency library.

`TypeError: functions.find is not a function
    at Strategy.passport.use.Strategy [as _verify] `

It seems that there's work arounds though listed in the issue- https://github.com/jaredhanson/passport/issues/421

Anyone else running into this issue? 

I may just be implementing the provider wrong. Looking further into the readMe and source code to see if I'm missing something.

**Comment by Babbz75** [comment]
Never mind the issue I was running into is resolved when adding a custom callback option in `strategyOptions`.

**Comment by iaincollins** [comment]
@Babbz75 Thanks for posting a followup!

[Provider configuration should be much simpler in version 2.0](#99)!
