### ISSUE TITLE
Will be this remade for nextjs api routes?

### ISSUE THREAD

**Issue by JurajJakubov** [iaincollins/next-auth#93]
Hi, i want to ask if is there any plan for remaking this into nextjs api routes? Thanks you very much.

**Comment by Gr8z** [comment]
+1

**Comment by akpenou** [comment]
+1

**Comment by iaincollins** [comment]
Hi @JurajJakubov 

Sorry for the delay in getting back to you.

For anyone wondering, yes, [yes, that's finally happing now](#99)!
